### ISSUE TITLE
Clean install of 21H1 does not run 5.12.1 and requires cumulative update 1151 or higher

### ISSUE THREAD

**Issue by Wiethoofd** [farag2/Sophia-Script-for-Windows#230]
On a clean installation of Windows 10, version 21H1, created with the MediaCreationTool from Microsoft which has not had and connection to the internet yet.

Tried to run the Sophia Script v 5.12.1 (created through Wrapper, but also manual execution) and refuses to run and throws the following error:

> WARNING: Windows 10 cumulative update installed: 928. The latest supported cumulative update: 1151 and higher. Please run Windows Update and try again.

Attached is the [Sophia_edited.ps1 file](https://github.com/farag2/Sophia-Script-for-Windows/files/6977882/Sophia_edited.txt) (as .txt) that was the output from the wrapper I tried to run through the 'Run powershell' as well as manually following [these steps](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use), resulting in the aforementioned error.

---
Ideally I want to be able to run this script on a clean install to prevent any needless stuff from being installed through WU and having to run the script again.

**Comment by farag2** [comment]
What's the problem to update the OS? I don't see any of them. I won't provide the ability to run on non-updated Win 10. But you may remove the appropriate checkings in the `Checkings` region in the module. And I don't guarantee that all all functions will work as they should.
