### ISSUE TITLE
Ethernet connection inconsistent after debloating.

### ISSUE THREAD

**Issue by Ivyishw** [farag2/Sophia-Script-for-Windows#232]
After debloating windows I noticed my ethernet connection was constantly dropping, I did speedtests and noticed my speed was drastically lower than it should be, especially for ethernet. I've restarted my router, used different ethernet ports and cables, troubleshoot on windows. I did update windows before debloating so its possible that the update has something to do with it. I would just use a restore point, but debloating has increased my performance by such a large amount that I would rather go through the trouble of finding the issue, Sorry if I said something stupid or didnt check something.

**Comment by farag2** [comment]
I don't any ethernet/network settings. So this isn't my or the script fault.
