### ISSUE TITLE
Don't remove "Send to" context menu from Sophia.ps1

### ISSUE THREAD

**Issue by Ferosauce** [farag2/Sophia-Script-for-Windows#233]

**Comment by farag2** [comment]
Have you confiagured the preset file before running?
Please read this: https://github.com/farag2/Sophia-Script-for-Windows#how-to-use
And this: https://github.com/farag2/Sophia-Script-for-Windows#how-to-run-the-specific-functions

After reading now you know what to do: find the appropriate function name `SendToContext -Show`, and invoke it.

```powershell
. .\Functions

Sophia -Functions "SendToContext -Show"
```

**Comment by Ferosauce** [comment]
But can you make it SendToContext -Show default instead of -Hide?

**Comment by farag2** [comment]
> But can you make it SendToContext -Show default instead of -Hide?

Users have to configure it before running, not me. This is just default preset. :)

**Comment by Ferosauce** [comment]
ok, i understand

**Comment by farag2** [comment]
Wait for https://github.com/Sophia-Community/SophiApp 😺
