### ISSUE TITLE
Windows 11 BitmapImageNewContext

### ISSUE THREAD

**Issue by jscorre1a** [farag2/Sophia-Script-for-Windows#235]
Fantastic work by the way.

So, hope you don't mind, I've got this error in your latest script for windows 11 (v6.0.2):
_**The term 'BitmapImageNewContext' is not recognized as the name of a cmdlet,**_

I didn't explored this frurther why this is.

Thanks again.

**Comment by farag2** [comment]
I know. Fixed in 6.0.3. many bugs fixed! I will release it today or tomorrow. If you don't want to wait you may download it from our Telegram group: https://t.me/sophia_chat/60733

**Comment by jscorre1a** [comment]
I can confirm it's solved and working wonderfully in the latest update. Congrats, and thank you.
