### ISSUE TITLE
DisableSearchBoxSuggestions should not be applied only to the US region

### ISSUE THREAD

**Issue by Hxppdv** [farag2/Sophia-Script-for-Windows#236]
According to [the description](https://www.tenforums.com/tutorials/25016-turn-off-search-online-include-web-results-windows-10-a.html) on tenforums, DisableSearchBoxSuggestions is used to turn off Search online and the web results. 
The description of the applicable area is as follows
> Bing "web" search results in Windows 10 is not available in all regions. It is available in at least the United States region.

It does not mean that web search is only available in the US region.
Also according to [Microsoft](https://support.microsoft.com/en-us/windows/web-search-in-windows-10-and-supported-regions-6c678e9c-fbed-a6d6-32c7-8bbf6d6cbea7), there are several regions that have web search support.

So I think it might be necessary to apply DisableSearchBoxSuggestions to these regions as well, or just apply it to all regions

**Comment by farag2** [comment]
It will be easier for me just to remove that checking.
