### ISSUE TITLE
Wrapper 2.3 some bugs...

### ISSUE THREAD

**Issue by Unixware** [farag2/Sophia-Script-for-Windows#246]
* The "Run Powershell" is disabled (can't be clicked)
* Also when I am importing my own script (import Sophia then some changes  and save them) it bugs me there is a "new sophia scipt on github" whatever I click there it deletes all the setups.

thanks!

**Comment by farag2** [comment]
I'll explain what you're dking wrong tomorrow). And send you 2.4.

**Comment by Unixware** [comment]
no problem,  thank you

anyway I am using Enterprise 20H2  - thats the issue maybe ..

**Comment by farag2** [comment]
No)

**Comment by ishanshLal-tRED** [comment]
so what's the problem and where is v2.4

**Comment by Unixware** [comment]
I mis-read the instructions on how to use the wrapper...  : now works for me, looks like the predef menu (Import Sophia) to add the  is not working correctly you need to import manually the sophia ps1 file

`UNZIP all the files and import the Sophia.ps1 preset file to import and to get the path for files to run. If you do not import Sophia.ps1 then you can not run directly the PowerShell script you create (Run PowerShell button is disabled) 

`

**Comment by ishanshLal-tRED** [comment]
in the menu bar <br>
![image](https://user-images.githubusercontent.com/61790879/132949509-b5f9dfdd-bc4f-456b-b1e0-52b55d50b588.png)
<br>I clicked the presets -> selected sophia script, <br>
inside console out-put i'm seeing all options enable as expected
however Run PowerShell is still disabled

**Comment by ishanshLal-tRED** [comment]
Ok now i get it, you need to use wrapper along with Sophia script functions (in my case Sophia.Script.v5.12.2.zip)

**Comment by farag2** [comment]
Hi. I'm not at my PC right now. BRB in the evening.

**Comment by farag2** [comment]
Please, test
[Sophia Script Wrapper v2.4.zip](https://github.com/farag2/Sophia-Script-for-Windows/files/7192105/Sophia.Script.Wrapper.v2.4.zip)
.
