### ISSUE TITLE
Getting errors in 21H1 - cannot complete in PowerShell

### ISSUE THREAD

**Issue by epicylon** [farag2/Sophia-Script-for-Windows#247]
![image](https://user-images.githubusercontent.com/1887101/133823412-3d9b6678-eedc-466f-9f1a-abed227ab1e3.png)

Tried running directly in PowerShell and Wrapper. Tried with "Checkings" on both "Warning" and "Checkings".

Tried with both regular version and PS7 version. 

Errors every time.

**Comment by farag2** [comment]
What about to rear the instruction? :)
https://github.com/farag2/Sophia-Script-for-Windows#how-to-use

**Comment by farag2** [comment]
The script has to be ran as administrator only. Everything is described in the manual. And about the wrapper, also.
Ah, you have managed? Working?

**Comment by epicylon** [comment]
It's working, probably had to do with the directory path being too long. Moved the script to a different directory - works flawlessly.

Sorry for not debugging more before opening a issue.

**Comment by farag2** [comment]
Really? Send please the whole path. May be this was a ug in the script.

**Comment by epicylon** [comment]
C:\Users\DASH\Documents\[XX]_EXEMPT\sophia_script\v5.12.2

**Comment by farag2** [comment]
Hm, it seems the path contains [ char. I need to do some tests. :)

**Comment by farag2** [comment]
Unfortunately, the Import-LocalizedData cmdlet doesn't support LiteralPath, so I can do nothing with this bug. :(
