### ISSUE TITLE
Displaying wrong string in drop down (DiagnosticDataLevel) in the Wrapper (german ui)

### ISSUE THREAD

**Issue by uDEV2019** [farag2/Sophia-Script-for-Windows#251]
at the option DiagnosticDataLevel under privacy and telemetry you have three options to choose (minimal, default, none).

In german, for minimal it shows a russian string.
![image](https://user-images.githubusercontent.com/51911097/134010140-04572e6f-2265-47cd-9603-429c21737ba3.png)

looked into the german wrapper translation and in the translation of the script and didn't found an issue.
When changing the ui to english or russian, the issue is gone. Back to german and you'll see the russian string.

**Comment by Henry2o1o** [comment]
I have changed it/some

**Comment by uDEV2019** [comment]
Ok, yesterday i had tomatos on my eyes...
