### ISSUE TITLE
#region Gaming  XboxGameTips - Disable None

### ISSUE THREAD

**Issue by Henry2o1o** [farag2/Sophia-Script-for-Windows#253]
![image](https://user-images.githubusercontent.com/6131799/134588050-b5b9cb3b-875e-4fa2-82fa-08d182802d88.png)

![image](https://user-images.githubusercontent.com/6131799/134588114-991f163c-2829-40da-bfcf-8eca332df83a.png)

None : The name "None" was not recognized as the name of a cmdlet, function, script file, or executable program.
executable program. Check the spelling of the name, or if the path is correct (if it is
included), and repeat the procedure.

**Comment by farag2** [comment]
This is not a legit function. May be this is a leftover from a buggy Wrapper version. Just remove it)

**Comment by Henry2o1o** [comment]
![image](https://user-images.githubusercontent.com/6131799/134588841-1f65ef90-ee39-4191-b938-7a6e60025674.png)

**Comment by farag2** [comment]
Hm...

**Comment by Henry2o1o** [comment]
"None" would be rather inappropriate there?

**Comment by farag2** [comment]
We'll check tomorrow

**Comment by Henry2o1o** [comment]
😉👍

**Comment by farag2** [comment]
I couldn't reproduce the bug...

**Comment by farag2** [comment]
So?..

**Comment by Henry2o1o** [comment]
![image](https://user-images.githubusercontent.com/6131799/134785766-54f002a7-c107-4f35-b265-f7405a515e39.png)
![image](https://user-images.githubusercontent.com/6131799/134785832-8f11dd5a-06ca-4515-b8b8-1fe8cd5d4d56.png)
👆 OK

![image](https://user-images.githubusercontent.com/6131799/134785855-ff20028c-dd94-4c52-8de1-1809c9ba1c36.png)
![image](https://user-images.githubusercontent.com/6131799/134785919-cd7c6872-8718-4a7e-9cd6-03566232504e.png)

**Comment by farag2** [comment]
I could reproduce it. It happens only for the German locale. :)

**Comment by Henry2o1o** [comment]
I just wrote about it. 👍

**Comment by Henry2o1o** [comment]
None - Nichts

**Comment by farag2** [comment]
> at None - Nichts

I still remember it from the Germal lessons. :)

**Comment by Henry2o1o** [comment]
#region Gaming
XboxGameTips -Disable
SetAppGraphicsPerformance

english

**Comment by Henry2o1o** [comment]
#region Gaming
XboxGameTips -Disable
SetAppGraphicsPerformance
![image](https://user-images.githubusercontent.com/6131799/134786170-1718cacd-efc1-4c54-aff3-ce0b06ce69c6.png)

**Comment by Henry2o1o** [comment]
#region Gaming
XboxGameTips -Disable
None
SetAppGraphicsPerformance
![image](https://user-images.githubusercontent.com/6131799/134786181-c540d0ee-cdec-421d-9385-2b1a755f1f8d.png)

**Comment by Henry2o1o** [comment]
In the script you write "None" for "Nothing".
Nothing should be added in the script for "Nothing".

**Comment by Henry2o1o** [comment]
Nothing changes nothing, so leave it out?

**Comment by farag2** [comment]
You offer to change `None` to `Nothing`? I meant that this option just doesn't invoke the function.

**Comment by Henry2o1o** [comment]
None - Nichts

#region Gaming
XboxGameTips -Disable
SetAppGraphicsPerformance

**Comment by farag2** [comment]
> None - Nichts

I've already downloaded you fixed translation.

**Comment by Henry2o1o** [comment]
If "Nothing" is selected, Sophia_edited.ps1 must not appear.

**Comment by farag2** [comment]
Nothing just means that this function won't be touch. Why a preset won;t be created?

**Comment by Henry2o1o** [comment]
If "Nothing" is selected, it must not appear in Sophia_edited.ps1.

**Comment by farag2** [comment]
I know it. I told David to fix it. xD

**Comment by Henry2o1o** [comment]
Difficult to explain 😉👍

**Comment by farag2** [comment]
I've understood the bug at once, but you started to explain where None should be placed. LOL 👍

**Comment by Henry2o1o** [comment]
So with "Nothing", no entry may appear in Sophia Edited.ps1.

**Comment by farag2** [comment]
🐱

**Comment by Henry2o1o** [comment]
No, not where it should be placed, but where it is currently located.
Small misunderstanding.

**Comment by Henry2o1o** [comment]
> I've understood the bug at once, but you started to explain where None should be placed. LOL 👍

No, not where it should be placed, but where it is currently located.
Small misunderstanding.

**Comment by farag2** [comment]
I'll send the fixed version. You'll test it)

**Comment by Henry2o1o** [comment]
OK

**Comment by farag2** [comment]
Already fixed in 2.5. ;)

**Comment by farag2** [comment]
fixed.
