### ISSUE TITLE
Disable windows update

### ISSUE THREAD

**Issue by Temtaime** [farag2/Sophia-Script-for-Windows#263]
Hello.
per https://docs.microsoft.com/en-us/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services#29-windows-update it's possible to disable windows update.
Is there any chance to add this feature ?

**Comment by farag2** [comment]
Sorry, but I will never allow to disable the WU via this script.

**Comment by agiz10** [comment]
Thank you for this link. Useful document.
