### ISSUE TITLE
feature: Return old context menu on Windows 11

### ISSUE THREAD

**Issue by krax1337** [farag2/Sophia-Script-for-Windows#266]
Привет! Можешь рассмотреть возможность включение опции возвращение старого контекстного меню на Windows 11. Это делается через редактирование параметров реестра.

Примеры:

> https://www.pcgamer.com/windows-11-context-menu-fix-right-click/
> https://appuals.com/disable-show-more-options-windows-11/

**Comment by farag2** [comment]
Already in development for the 6.0.6 release.
