### ISSUE TITLE
Set-WinDefaultInputMethodOverride hangs indefinitely on Windows 11

### ISSUE THREAD

**Issue by HouzuoGuo** [farag2/Sophia-Script-for-Windows#272]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [**Before running**](https://github.com/farag2/Sophia-Script-for-Windows#fire-before-running-fire).
- [X] Refer to the [**How to use**](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use).
- [ ] If you issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

Here's the snippet from `Sophia.ps1`:

```
...
IPv6Component -Enable

# Override for default input method: English
# Переопределить метод ввода по умолчанию: английский
InputMethod -English
```

Here's the PS debug trace:

```
DEBUG:     ! SET $__cmdletization_methodInvocationInfo = 'Microsoft.PowerShell.Cmd...'.
DEBUG:  561+        >>>> $__cmdletization_passThru = $false
DEBUG:     ! SET $__cmdletization_passThru = 'False'.
DEBUG:  562+             if ( >>>> $PSBoundParameters.ContainsKey('InputObject')) {
DEBUG:  565+                  >>>> $__cmdletization_objectModelWrapper.ProcessRecord($__cmdletization_queryBuilder,
$__cmdletization_methodInvocationInfo, $__cmdletization_PassThru)
DEBUG:  542+     switch -exact ( >>>> $PSCmdlet.ParameterSetName) {
DEBUG:     ! SET $switch = ''.
DEBUG:  577+      >>>> }
DEBUG:  580+     End  >>>> {
DEBUG:     ! CALL function 'Enable-NetAdapterBinding<End>'
DEBUG:  583+             if ( >>>> -not $__cmdletization_exceptionHasBeenThrown)
DEBUG:  585+                  >>>> $__cmdletization_objectModelWrapper.EndProcessing()
DEBUG:  592+      >>>> }
DEBUG: 5406+  switch ( >>>> $PSCmdlet.ParameterSetName)
DEBUG:     ! SET $switch = ''.
DEBUG: 5423+  >>>> }
DEBUG:  723+  >>>> InputMethod -English
DEBUG: 5445+  >>>> {
DEBUG:     ! CALL function 'InputMethod'  (defined in file 'C:\hg\win\sophia-scripts\Module\Sophia.psm1')
DEBUG:     ! SET $switch = 'IEnumerator'.
DEBUG: 5463+  switch ( >>>> $PSCmdlet.ParameterSetName)
DEBUG: 5465+    >>>> "English"
DEBUG: 5467+     >>>> Set-WinDefaultInputMethodOverride -InputTip "0409:00000409"
```

Then it hangs indefinitely. When `InputMethod -English` is commented out, the script completes successfully without further issues.

The host OS is a fully patched Windows 11, the PS version table reads:

```
Name                           Value
----                           -----
PSVersion                      5.1.22000.65
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.65
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by HouzuoGuo** [comment]
Strange indeed! Reboot doesn't really help though.

I wonder if this is a windows bug - the computer was running Win10 before and I ran sophia script (for win10) at the same configuration each week. This bug started to occur only after the computer got a win11 upgrade.

**Comment by farag2** [comment]
For sure, the upgrade is the cause. More over, I found yesterday that all my custom tasks in the task scheduler refused even to start. I mean, they don't crash, just didn't react on the start button pressing. Had to re-create all of them. And this happened on a clean 11.
Probably, check the OS for the integrity:

```powershell
Repair-WindowsImage -Online -RestoreHealth
```

then

```powershell
sfc /scannow
```

**Comment by farag2** [comment]
So as I stated above, this is a Windows bug and this small cmdlet cannot be rewritten. :)
