### ISSUE TITLE
script execution freezes for ~ 20 min on 2nd start

### ISSUE THREAD

**Issue by deGoyan** [farag2/Sophia-Script-for-Windows#285]
### Prerequisites

- [x] Verify that this is not a Windows issue;
- [x] Refer to the [**Before running**](https://github.com/farag2/Sophia-Script-for-Windows#fire-before-running-fire).
- [x] Refer to the [**How to use**](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use).
- [ ] If you issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

![image](https://user-images.githubusercontent.com/41890015/140036358-8cb8e8ca-ba89-4c08-a17d-101ddff77c36.png)

**Comment by farag2** [comment]
А если нажать любую кнопку, кроме Enter, в окне консоли? То, что пошик зависает, это нормально. Вот если совсем зависло, то я тут бессилен. Значит, что-то сломано в ОС.

**Comment by farag2** [comment]
Можешь включить Transscript в пресете и запустить опять модель?

**Comment by farag2** [comment]
👿

**Comment by deGoyan** [comment]
> 
> 
> А если нажать любую кнопку, кроме Enter, в окне консоли? То, что пошик зависает, это нормально. Вот если совсем зависло, то я тут бессилен. Значит, что-то сломано в ОС.

Ни на какие кнопки не реагирует.

**Comment by deGoyan** [comment]
> 
> 
> Можешь включить Transscript в пресете и запустить опять модель?

При следующем воспроизведении попробую

**Comment by deGoyan** [comment]
> 
> 
> 👿

Торопыга)

**Comment by farag2** [comment]
> 
> 
> > Можешь включить Transscript в пресете и запустить опять модель?
> 
> При следующем воспроизведении попробую

Тогда можно лишь удаленно глянуть, что творится. Столько тысяч раз запускалось все... Могу через TeamViewer.
