### ISSUE TITLE
Suspicious behavior 

### ISSUE THREAD

**Issue by Serpher1** [farag2/Sophia-Script-for-Windows#287]
### Prerequisites

- [x] Verify that this is not a Windows issue;
- [x] Refer to the [**Before running**](https://github.com/farag2/Sophia-Script-for-Windows#fire-before-running-fire).
- [x] Refer to the [**How to use**](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use).
- [ ] If you issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

So, care to explain why your script tries to embed Rozena_GenA malware tool while running? I'm talking about weird dll's generating in temp folder.

[Screenshot](https://imgur.com/8vYfhnO)

**Comment by farag2** [comment]
Why suspicious? :D
Please provide the whole folder from which you ran the script.

**Comment by farag2** [comment]
So?..

**Comment by Serpher1** [comment]
It is on admin account and run with admin privileges but ESET classified this as rozena trojan.

**Comment by farag2** [comment]
This is very funny. Report ESET that's a false positive. I can't fix it. The error is very simple: you have no access to this folder...
