### ISSUE TITLE
WSL distro not installing

### ISSUE THREAD

**Issue by 0xShkk** [farag2/Sophia-Script-for-Windows#288]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [**Before running**](https://github.com/farag2/Sophia-Script-for-Windows#fire-before-running-fire).
- [X] Refer to the [**How to use**](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use).
- [ ] If you issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

Hi,

thank you for this great script and ongoing development!
I just used it to setup few Windows fresh installs.

I have noticed that WSL itself will be installed in version 2 but when a distro is choosen, it wont install.
Instead, the GUI keeps on coming back but no distro is installed.

**Comment by farag2** [comment]
Ha. :) The GUI doesn't disappear by design. It works. You just need to reoot. Only after that WSL will be triggered and start downloading a distro. Please, check again.

**Comment by farag2** [comment]
As I stated before, everything works: I just ran `WSL` function, reboot, and Debian (in my case) started installing.

```powershell
wsl.exe --install --distribution Ubuntu
```

This is the command that is used in the module under the hood. Please, run it directly and reboot.

**Comment by farag2** [comment]
![Снимок экрана (4)](https://user-images.githubusercontent.com/10544660/139581867-ba968077-2d50-406e-ae8a-559b54372ba0.png)

**Comment by 0xShkk** [comment]
Thank you for the clarification!
