### ISSUE TITLE
[Feature request] Add option to show all tray icons at the taskbar

### ISSUE THREAD

**Issue by 0xShkk** [farag2/Sophia-Script-for-Windows#289]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [**Before running**](https://github.com/farag2/Sophia-Script-for-Windows#fire-before-running-fire).
- [X] Refer to the [**How to use**](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use).
- [ ] If you issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

I missed the option to show all tray icons.

Can you please add this?

As the wrapper is also affected, I mention @BenchTweakGaming

This can be achived by 

```
Function ShowTrayIcons {
	If (!(Test-Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer")) {
		New-Item -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer" | Out-Null
	}
	Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer" -Name "NoAutoTrayNotify" -Type DWord -Value 1
}
```

**Comment by farag2** [comment]
For 11?

**Comment by 0xShkk** [comment]
The suggested registry setting was for Windows 10.
This should work on Home editions too, no matter if its added to policies (it will be applied to local GPO / same as gpedit.msc for non domain joined clients).

However, I have just tried Windows 11 and you are perfectly right!
They banned the setting to always show taskbar icons, and if you do a workaround it gets reset after reboot...
What a stupid addon to Win11!
