### ISSUE TITLE
Windows 10 LTSC 21H2 support

### ISSUE THREAD

**Issue by Forsakenrox** [farag2/Sophia-Script-for-Windows#297]
Need add support a new version of Windows 10 LTSC 21H2

**Comment by farag2** [comment]
You're Nostradamus)
Already. But didn't create a new release. Tomorrow.

<https://github.com/farag2/Sophia-Script-for-Windows/tree/master/Sophia%20Script/Sophia%20Script%20for%20Windows%2010%20LTSC%202021>
