### ISSUE TITLE
Start menu apps and weather notification not removed

### ISSUE THREAD

**Issue by vinibortoletto** [farag2/Sophia-Script-for-Windows#308]
### Prerequisites

- [x] Verify that this is not a Windows issue;
- [ ] Refer to the [**Before running**](https://github.com/farag2/Sophia-Script-for-Windows#fire-before-running-fire).
- [ ] Refer to the [**How to use**](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use).
- [ ] If you issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

I just ran the script in a fresh install and noticed the Start Menu apps and weather notification on the taskbar are not being removed.

**Comment by farag2** [comment]
I know about the bug with weather notification. But regarding Start icons, they are just icons, not installed apps. You may use the function to unpin them all.

**Comment by farag2** [comment]
This is strange but today I cannot catch the bug with the weather notification. The fucntion (that is very primitive) now always works...
