### ISSUE TITLE
Sophia.psm1:193 Zeichen:3

### ISSUE THREAD

**Issue by Henry2o1o** [farag2/Sophia-Script-for-Windows#312]
![image](https://user-images.githubusercontent.com/6131799/146216523-505d237e-80cd-4139-b49b-a63ea384a8a7.png)

**Comment by farag2** [comment]
Please, attach the whole archive with all files to test. I didn't have such error.

**Comment by Henry2o1o** [comment]
![image](https://user-images.githubusercontent.com/6131799/146223579-65718136-be2f-418d-8be8-23b6cbc20bf0.png)

**Comment by farag2** [comment]
Still waiting the archive...

**Comment by Henry2o1o** [comment]
https://github.com/farag2/Sophia-Script-for-Windows/releases/download/6.0.9/Sophia.Script.Wrapper.v2.5.3.zip
https://github.com/farag2/Sophia-Script-for-Windows/releases/download/6.0.9/Sophia.Script.for.Windows.11.v6.0.9.zip

just downloaded again

**Comment by farag2** [comment]
And still get the error?

**Comment by Henry2o1o** [comment]
yes

**Comment by farag2** [comment]
That's a pity. I'll do some tests in an hour.

**Comment by Henry2o1o** [comment]
script only imported without changing anything

![image](https://user-images.githubusercontent.com/6131799/146236958-794b14eb-18dd-4ee3-90a3-940510bfdc49.png)

**Comment by farag2** [comment]
The insider Windows isn't supported. May be this is the cause.

**Comment by Henry2o1o** [comment]
🤷‍♂️

**Comment by Henry2o1o** [comment]
```
# Get the name of a preset (e.g Sophia.ps1) regardless it was named
		$PresetName = Split-Path -Path ((Get-PSCallStack).Position | Where-Object -FilterScript {$null -eq $_.File}).Text -Leaf
```

**Comment by farag2** [comment]
I got the point.

**Comment by Henry2o1o** [comment]
has nothing to do with the insider

**Comment by farag2** [comment]
Fixed. Will upload soon.

**Comment by farag2** [comment]
https://github.com/farag2/Sophia-Script-for-Windows/releases/tag/6.0.10
