### ISSUE TITLE
Running script opens windows update.

### ISSUE THREAD

**Issue by kangarooo** [farag2/Sophia-Script-for-Windows#314]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [**Before running**](https://github.com/farag2/Sophia-Script-for-Windows#fire-before-running-fire).
- [X] Refer to the [**How to use**](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use).
- [X] If you issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

Running script opens windows update. No script was executed.
Windows 10 20h2 19042.985
![image](https://user-images.githubusercontent.com/73187/146686871-90cef621-0e8d-4e97-a170-e70fcb39a2e0.png)

**Comment by farag2** [comment]
Any screenshots?

**Comment by farag2** [comment]
As I may see, your 10 isn't up-to-date. You need to update it.
Check the minimum build required.
https://github.com/farag2/Sophia-Script-for-Windows#windows-10

Please, read the error comments next time. It's very simple.

**Comment by kangarooo** [comment]
So i just wanted to try like im later in setup putting shutup o o https://www.oo-software.com/en/shutup10
and 1 year thing i usually use and works out of box is https://github.com/Disassembler0/Win10-Initial-Setup-Script
It still works, just wanted to try this on new installed computer.

i dont have time for reading about why app isnt working.
I dont want updates, i want it work out of box.
I want no updates. I want no more bloatware, so i wanted to try this script, i wanted no more bloatware updates, so i wanted to try this script.
This script asks me to update bloatware?

**Comment by farag2** [comment]
The script requires Windows to has 1151 version at least. I closed "the issue". If you do not want to read and provide any screens, it's up to you. I strongly advice to update your OS before executing my module. And I don't advice to apply any abandoned scripts like from Disassembler0. It was good. But now the maintainer doesn't support it any more.

**Comment by kangarooo** [comment]
I updated screen. Its fresh installation, i want to remove bloatware, not update it.

**Comment by farag2** [comment]
This is a myth that Windows contains any bloatware... If you run the Windows Update, it won't update any so called bloatware. Otherwise, the module won't let you run it (unless you won't edit the module code, of course). This is the Bible: module does checkings before the running.
