### ISSUE TITLE
Disabling UAC

### ISSUE THREAD

**Issue by CaptainFrosty** [farag2/Sophia-Script-for-Windows#321]
Hi, this isn't an error or unexpected behavior. My apologies. I really like your script; it's great. I feel compelled though to speak up about the wisdom of having UAC disabled by default on the preset. Mainly for less experienced people who might be using it. From a security perspective, it's a bad idea. UAC is annoying, no doubt about that. But it isn't just a nag screen to remind you are an admin. That's the least of its functions. Sometimes it is the only thing standing between malware and full permissions to your file system. 

I learned this from experience in my younger and more foolish days, when I could have prevented a system from being totally trashed simply by having had UAC on. I, with my merely human reflexes, certainly couldn't have outpaced a virus that was doing tons of operations in a matter of seconds. It could, though. I am aware there exists plenty of malware capable of defeating it to varying degrees. But even if it were only, say, 10% effective, that's a last line of defense you're turning off for the sake of small convenience. 

For the record, I do turn the dimming off. That might be a better preset and let the user be responsible for making changes. 

If you made it here, thanks for taking the time to listen to my spiel and of course you are under no obligation to follow my advice, but I hope you'll take it into consideration.

[https://www.howtogeek.com/124754/htg-explains-why-you-shouldnt-disable-uac/](https://www.howtogeek.com/124754/htg-explains-why-you-shouldnt-disable-uac/)

**Comment by farag2** [comment]
I'll read somewhere tomorrow. 🤙

**Comment by farag2** [comment]
In two words: I don't disable UAC. I disable...

https://github.com/farag2/Sophia-Script-for-Windows/blob/6b23fcde50d7e6841afa078c964bb41a3c9c92bc/Sophia%20Script/Sophia%20Script%20for%20Windows%2010/Module/Sophia.psm1#L4309

Don't get confused.:)

**Comment by Panja0** [comment]
> 

Could you explain the difference please?

**Comment by farag2** [comment]
UAC is the feature itself. This is how the OS reacts on any executables being called. I only set ```Notify me only when apps try to make changes to my computer```. So this configuration doesn't disable UAC as a feature, it only doesn't let a prompt pop up when you run any admin-based executable files. UAC is still running under the hood.

> UAC is annoying, no doubt about that. But it isn't just a nag screen to remind you are an admin.

Totally agree with you. But my default preset is just an example for users. I do not make them use it as out-of-the-box preset. Use you brain, Luke! :) I heard about the suggetion many times, but I'm standing my ground that such scripts are made not for noobies, but tech-savvies.
In our next project, [SophiApp](https://github.com/Sophia-Community/SophiApp), there is no preset file, it's up to user what to enable and disable. Of course the GUI displays the actual state of every function. Have a nice day. SophiApp 1.0 stable will be released sowhere in March.

**Comment by CaptainFrosty** [comment]
@farag2 Hey, my apologies, this got lost in my notifications somehow. Also sorry for the misunderstanding. I should have looked at the script more closely and realized it was applying GPOs to fine-tune the UAC settings, which I knew about. Clearly a misapplication of my two cents. Probably didn't need to link that stupid website, either. Guess I felt like I needed backup. Live long and prosper.
