### ISSUE TITLE
Doesnt run in 32-bit

### ISSUE THREAD

**Issue by kangarooo** [farag2/Sophia-Script-for-Windows#322]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [**Before running**](https://github.com/farag2/Sophia-Script-for-Windows#fire-before-running-fire).
- [X] Refer to the [**How to use**](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use).
- [X] If you issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

I thought it was cause i first run most popular debloater https://github.com/Sycnex/Windows10Debloater
But that doesnt have option to remove also built in media player and audio player so i wanted to try Sophia again.
But turns out its writing about 64-bit system not here but 32-bit windows 10.

`Import-Module : **The current processor architecture is: X86.**  The module 'C:\Users\User\Downloads\Sophia Script for Windows 10
v5.12.10\Manifest\Sophia.psd1' **requires the following architecture: Amd64.**
At C:\Users\User\Downloads\Sophia Script for Windows 10 v5.12.10\Sophia.ps1:77 char:1
+ Import-Module -Name $PSScriptRoot\Manifest\Sophia.psd1 -PassThru -For ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Users\User\D...est\Sophia.psd1:String) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : Modules_InvalidProcessorArchitecture,Microsoft.PowerShell.Commands.ImportModuleCommand

Checkings : The term 'Checkings' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of
the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\User\Downloads\Sophia Script for Windows 10 v5.12.10\Sophia.ps1:116 char:1
+ Checkings -Warning
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Checkings:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

CreateRestorePoint : The term 'CreateRestorePoint' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\User\Downloads\Sophia Script for Windows 10 v5.12.10\Sophia.ps1:129 char:1
+ CreateRestorePoint
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (CreateRestorePoint:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

DiagTrackService : The term 'DiagTrackService' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\User\Downloads\Sophia Script for Windows 10 v5.12.10\Sophia.ps1:135 char:1
+ DiagTrackService -Disable
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (DiagTrackService:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

**Comment by farag2** [comment]
Sophia Script never supported 32-bit OS. So there is no option to make it work on Windows x86. Sorry. The 32-bit OS times has ended many years ago. Windows 11 even has no x86 build.
