### ISSUE TITLE
Error in the store.

### ISSUE THREAD

**Issue by StrikerOnLine** [farag2/Sophia-Script-for-Windows#325]
After running Sophia the login in the store games does not work, what is the solution?

**Comment by farag2** [comment]
May be you removed Xbox related packages? Send your preset, please.

**Comment by farag2** [comment]
🤔

**Comment by farag2** [comment]
As I didn't get any feedback, this is my guess-works: install all Xbox related packages back: 

<https://www.microsoft.com/store/productId/9WZDNCRD1HKW>
<https://www.microsoft.com/store/productId/9WZDNCRFJBD8>
<https://www.microsoft.com/store/productId/9mv0b5hzvk9z>
<https://www.microsoft.com/store/productId/9NBLGGH537C2>
<https://www.microsoft.com/store/productId/9NKNC0LD5NN6>
<https://www.microsoft.com/store/productId/9NZKPSTSNW4P>

**Comment by farag2** [comment]
Hi! Removing any Xbox related packages don't break Store functionality. :)
If you want to install all Store related packages download what you want from my cloud: https://disk.yandex.ru/client/disk/Программы/Inbox%20Apps

Also you can do this: `wsreset -i` (as admin in PowerShell). It will restore all necessary packages at once by downloading them from MS recource.

Also you may try to restore any packages (if they weren't removed from system account) by calling `RestoreUWPApps` function from my script.
