### ISSUE TITLE
21h2 sfc/ scannow problem

### ISSUE THREAD

**Issue by Galamooth** [farag2/Sophia-Script-for-Windows#334]
I am on windows 10 64bits home edition 21h2 build 19044.1620. I have done a clean install of windows installed all drivers and updates correctly, everything works perfect and sfc /scannow takes about 2 minutes to complete. Then I used sophia script for version 21h2 restart windows and now sfc /scannow does not advance, it stops at 57% after about 5 minutes it advances to 93% and there it stays. Why is this happening? It can be fixed? Thanks!

**Comment by farag2** [comment]
Hi. Thanks for asking, but I'm sure this is not the module fault. Any of settings have no such effect. Actually, `sfc /scannow` does nothing with the main command. Please run in this subsequence

```
Repair-WindowsImage -Online -RestoreHealth
sfc /scannow
```

**Comment by Galamooth** [comment]
Translator please.
Bien. Veré si funciona. Pero tengo otro problema que al parecer sucede
despues de aplicar sophia script. Y es que epic games ahora no abre,
aparece en ejecución en el administrador de tareas pero no se ejecuta en
pantalla. Me pregunto si es posible que sophia tenga algo que ver. Gracias
por responder :)

**Comment by Galamooth** [comment]
Muchas gracias, no usare sophia por el momento, he formateado ya 2 veces y
todo va bien antes de usarlo. No sé que pueda ser el problema. Espero se
pueda reparar proximamente. Si es que fuera un problema real. Gracias por
tu tiempo. Saludos

**Comment by farag2** [comment]
Which game you cannot open? And what error appears?

**Comment by Galamooth** [comment]
El iniciador de epic games no abre. Antes de sophia abria bien despues lo
abro y no pasa nada. Pero en el administrador de tareas se está
ejecutando.  Uso también wpd para la privacidad. Pero ya hablé con ellos y
dicen que posiblemente es sophia así que por eso les pregunto a ustedes :)

**Comment by farag2** [comment]
Ha-ha, nice dialogue you had with them. I'm pointing at their so-called privacy app that does nothing. Well, I have free time to check by myself via TeamViewer and you will show me the error. DM me via Telegram: https://t.me/sanctuary_d
What morons are they...

**Comment by Galamooth** [comment]
Muy bien regresando a casa me contactare para revisar, hasta entonces! Y
gracias otravez!

**Comment by farag2** [comment]
Are you @smithdron in telegram. Someone sent me a Duck. :)

**Comment by Galamooth** [comment]
No, I'm not.

**Comment by farag2** [comment]
LOL. As I sent you my TG acc, someone sent a Duck. I thought that was you. LOOOOL. I replied him that he's extremely fast. Asked him about the ID and pass. HE disappeared thinking that I gone mad. Still hasn't explained what he wants. The life is amazing. ))

**Comment by Galamooth** [comment]
Jajajjaa. Estoy en el trabajo. Pero regresando a casa te contacto para
poder hablar sobre esto amigo gracias por tener la atención conmigo. 😁

**Comment by Galamooth** [comment]
Confirmo que el problema es sophia script. No sé que hace pero no permite ejecutar correctamente aplicaciones. Msi como epic launcher o no se si es solo problema con ese programa. Pero volví a formatear la pc hice todo igual incluyendo wpd y omití a sophia....  Epic games y cualquier..msi funcionan correctamente. Debería verificar el script. Gracias

**Comment by farag2** [comment]
I'm ready to test. Waiting for you in TG. I have many questions.

**Comment by Galamooth** [comment]
Estoy tratando de escribirte por telegram pero no me deja

**Comment by Galamooth** [comment]
Estoy usando Telegram para chatear. ¡Únete! Descárgala aquí:
https://telegram.org/dl

**Comment by farag2** [comment]
Yes, you need the app and register there)

**Comment by Galamooth** [comment]
Ya lo hice. Pero no me deja enviar mensaje

**Comment by farag2** [comment]
Any luck? I have no idea why cannot use Telegram))

**Comment by Galamooth** [comment]
Si gustas algún otro medio de comunicación para contactarnos directamente,
hasta ahora todo va bien y estable con mi computador. Sólo no usé sophia.
Aquí es de madrugada, pero mañana descanso del trabajo. Podemos ponernos de
acuerdo. Solo dime algún medio para comunicarnos. Que no sea facebook jeje.

**Comment by Galamooth** [comment]
Hello! In that case, you can enter through the invitation link or if an
administrator with whom you are mutual contacts adds you (that is, both
have been added as contacts with their respective phone numbers).

**Comment by Galamooth** [comment]
Esto dice telegram

¡Gracias! Tu queja ha sido enviada satisfactoriamente. El supervisor de
nuestro equipo la revisará cuanto antes. Si fue un error, todas las
limitaciones serán levantadas de tu cuenta pronto.

**Comment by farag2** [comment]
I don't understand... My link is enough to enter the chat with... I don't use any of socials. :) Telegram only: https://t.me/sanctuary_d
Keep my informed what's going on when you click on the URL. Does in redirect you to the Telegram app? Attach the screenshot.

**Comment by farag2** [comment]
> In that case, you can enter through the invitation link

But this is not the invitation link, this is link of mine!

**Comment by Galamooth** [comment]
Tengo limitada mi cuenta, no sé por qué. Dicen que me enviaran una
respuesta pronto. Lo que sucede es que después de aplicar sophia.
Simplemente epic games no abre.  Pero si se ejecuta en el administrador de
tareas. Eso es todo. Extraño no?  No lo he instalado por que me jode el pc
jejeje tampoco abre discord. Y en general cualquier. Msi.espero una
respuesta de telegram mañana. Y te aviso. Gracias por intentar dar
solución. Por cierto. Tu eres el creador del script?

**Comment by farag2** [comment]
Yes. Ha-ha. Do you see all commits made by me: https://github.com/farag2/Sophia-Script-for-Windows/commits/master
https://github.com/farag2/farag2

> Simplemente epic games no abre.

I need to see how does it occur. Nobody had such bug. Actually, this is impossible: Sophia is just a PowerShell module. Anyway, could you install Telegram on phone?
