### ISSUE TITLE
Dont support 22581.100

### ISSUE THREAD

**Issue by pomazanbohdan** [farag2/Sophia-Script-for-Windows#336]
### Prerequisites

- [ ] Verify that this is not a Windows issue;
- [ ] Refer to the [**Before running**](https://github.com/farag2/Sophia-Script-for-Windows#fire-before-running-fire).
- [ ] Refer to the [**How to use**](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use).
- [ ] If you issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

Dont support 22581.100
![image](https://user-images.githubusercontent.com/696713/160392596-eedc05f4-b3cf-4b40-be61-d545b6047215.png)

**Comment by farag2** [comment]
Hi. You want me to add the Insider support? :)

**Comment by pomazanbohdan** [comment]
https://github.com/Sophia-Community/SophiApp/issues/40

**Comment by farag2** [comment]
Actually, just comment out these strings

https://github.com/farag2/Sophia-Script-for-Windows/blob/8bd5f06498f00fc00d32690ce06f762a36c18506/Sophia%20Script/Sophia%20Script%20for%20Windows%2011/Module/Sophia.psm1#L65

https://github.com/farag2/Sophia-Script-for-Windows/blob/8bd5f06498f00fc00d32690ce06f762a36c18506/Sophia%20Script/Sophia%20Script%20for%20Windows%2011/Module/Sophia.psm1#L90

**Comment by farag2** [comment]
Do you understand the Russian language? 🐱

**Comment by farag2** [comment]
Fixed in 6.0.14
