### ISSUE TITLE
OpenWindowsTerminalAdminContext, issue when launch a Directory ending with a Backslash (fix included!)

### ISSUE THREAD

**Issue by fuba82** [farag2/Sophia-Script-for-Windows#340]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [**Before running**](https://github.com/farag2/Sophia-Script-for-Windows#fire-before-running-fire).
- [X] Refer to the [**How to use**](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use).
- [ ] If you issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

hi there,
as already known here: https://github.com/microsoft/terminal/issues/4571
Windows Terminal has an issue to launch from a Directory with a Backslash at the end.

To fix this also for your script, you need to change:
``wt.exe -d "%V"`` to ``wt.exe -d "%V\."``
and it will work again in both, with and without ending Backslash!

gretings

**Comment by farag2** [comment]
Hi. I heard about that issue. Is it really happen? How can reproduce it?

**Comment by fuba82** [comment]
> Hi. I heard about that issue. Is it really happen? How can I reproduce it?

hmm, let me think how can you reproduce:  
 >  launch from a Directory with a Backslash at the end
  
Well... An Example:  
``wt.exe -d "C:\"`` or ``wt.exe -d "C:\Users\"`` or ``wt.exe -d "C:\Program Files\"`` or... as mentioned before: 
**ANY other Directory with a Backslash at the end**  
  
sorry for my sarcasm, but i can't get more clear because the issue is the answer "how to reproduce" 🤣

**Comment by farag2** [comment]
Well, I have time to get down to your so-called issue. Hm, I still cannot get the point where is the issue in the script. The context menu the script creates works from a GUI, so how this bug can be reproduced within it? I know how it works using a CLI, but within a GUI? Could you record a GIF with the bug?

**Comment by fuba82** [comment]
> Well, I have time to get down to your so-called issue. Hm, I still cannot get the point where is the issue in the script. The context menu the script creates works from a GUI, so how this bug can be reproduced within it? I know how it works using a CLI, but within a GUI? Could you record a GIF with the bug?

Just... No!
I can not because i fixed the bug/issue already and im not willing to revert it.  
  
It was just a recommendation to fix the bug in your script, so you can either use it or ignore it -> your choise!  
  
if you can **not** reproduce it with ALL the "more then clear" information WHY and HOW the Bug occurs (with also an external link in the WT Repository), and also gave you ALL the information you need to fix it, i really can not help you...

gl

**Comment by farag2** [comment]
Implemented in 6.1.0. LOL :)
