### ISSUE TITLE
[Question] Default values

### ISSUE THREAD

**Issue by Obegg** [farag2/Sophia-Script-for-Windows#346]
### Prerequisites

- [ ] Verify that this is not a Windows issue;
- [ ] Refer to the [**Before running**](https://github.com/farag2/Sophia-Script-for-Windows#fire-before-running-fire).
- [ ] Refer to the [**How to use**](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use).
- [ ] If you issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

```
<#
	Disable the Internet Protocol Version 6 (TCP/IPv6) component for all network connections
	Before invoking the function, a check will be run whether your ISP supports the IPv6 protocol using https://ipv6-test.com

	Выключить IP версии 6 (TCP/IPv6)
	Перед выполнением функции будет провердена проверка: поддерживает ли ваш провайдер IPv6, используя ресурс https://ipv6-test.com
#>
IPv6Component -Disable
```
IPv6 is modern and getting popular nowadays, why would the script disable it by default? It should be turned on.

```
#region OneDrive
# Uninstall OneDrive. The OneDrive user folder won't be removed
# Удалить OneDrive. Папка пользователя OneDrive не будет удалена
# OneDrive -Uninstall
```
OneDrive should be uninstalled by default

**Comment by farag2** [comment]
Hi. This is just a default preset. You have to configure it manually before running. What about OneDrive shouldn't be uninstalled be default, and IPv6 is of course modern, and it is disabled by default: if you look into the code, I check whether ISP supports it or not. And according to it, it will be disabled even if you configured it so.

**Comment by Obegg** [comment]
Thank you for your answer. You said I have to configure it manually, it makes me think - there isn't a "recommended" setting so it would be easier for others to simply run without configuring it manually one by one?

**Comment by farag2** [comment]
if you want, you may consider the current preset as a recommended one, but it doesn't deliver users from configuring it anyway. This is their OSes, not mine.
