### ISSUE TITLE
[Suggestion] Install the latest .NET (6.0)

### ISSUE THREAD

**Issue by Obegg** [farag2/Sophia-Script-for-Windows#347]
The script has the option to ```Install the latest Microsoft Visual C++ Redistributable Packages 2015–2022 x64```:

```
<#
	Install the latest Microsoft Visual C++ Redistributable Packages 2015–2022 x64
	Установить последнюю версию распространяемых пакетов Microsoft Visual C++ 2015–2022 x64
	https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist
#>
InstallVCRedistx64
```

So why not add the option to install the latest .NET?
https://dotnet.microsoft.com/en-us/download

**Comment by farag2** [comment]
❤️

**Comment by farag2** [comment]
```powershell
if (Get-AppxPackage -Name Microsoft.DesktopAppInstaller)
{
	winget install --id=Microsoft.DotNet.DesktopRuntime.6 --exact --accept-source-agreements
}
else
{
# https://github.com/dotnet/core/blob/main/release-notes/releases-index.json
$Parameters = @{
	Uri              = "https://raw.githubusercontent.com/dotnet/core/main/release-notes/releases-index.json"
	UseBasicParsing  = $true
}
$LatestRelease = ((Invoke-RestMethod @Parameters)."releases-index" | Where-Object -FilterScript {$_."channel-version" -eq "6.0"})."latest-release"
$DownloadsFolder = Get-ItemPropertyValue -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" -Name "{374DE290-123F-4565-9164-39C4925E467B}"

$Parameters = @{
	Uri             = "https://dotnetcli.azureedge.net/dotnet/Runtime/$LatestRelease/dotnet-runtime-$LatestRelease-win-x64.exe"
	OutFile         = "$DownloadsFolder\dotnet-runtime-$LatestRelease-win-x64.exe"
	UseBasicParsing = $true
	Verbose         = $true
}
Invoke-WebRequest @Parameters

Start-Process -FilePath "$DownloadsFolder\dotnet-runtime-$LatestRelease-win-x64.exe" -ArgumentList "/install /passive /norestart" -Wait

<#
	PowerShell 5.1 (7.2 too) interprets the 8.3 file name literally, if an environment variable contains a non-latin word,
	so you won't be able to remove "$env:TEMP\dd_vcredist_amd64_*.log" file explicitly

	Another ways to get normal path to %TEMP%
	[Environment]::GetEnvironmentVariable("TEMP", "User")
	(Get-ItemProperty -Path HKCU:\Environment -Name TEMP).TEMP
	[System.IO.Path]::GetTempPath()
#>
Get-ChildItem -Path "$DownloadsFolder\dotnet-runtime-$LatestRelease-win-x64.exe", "$env:TEMP\Microsoft_.NET_Runtime_*.log" -Force | Remove-Item -Recurse -Force -ErrorAction Ignore
```

Soon will be implemented in 6.0.15

**Comment by pratyakshm** [comment]
@farag2 Why don't you check directly if winget is registered on OS using 
```powershell
Get-Command winget
```
instead of
```powershell
Get-AppxPackage -Name Microsoft.DesktopAppInstaller
```

**Comment by farag2** [comment]
Because this is not the command to check. :)

**Comment by pratyakshm** [comment]
> Because this is not the command to check. :)

In L1 of https://github.com/farag2/Sophia-Script-for-Windows/issues/347#issuecomment-1141488397, you intend to check if winget is installed, right?

**Comment by farag2** [comment]
Yeah, It's .

**Comment by pratyakshm** [comment]
> Yeah, It's .

Yeah, so as I said before, you may use 
```
Get-Command winget
```
to check if winget.exe is registered.

Do you mind explaining what you mean when you say that this isn't the command to check?

**Comment by farag2** [comment]
I prefer to check whether the package is installed))

**Comment by pratyakshm** [comment]
> I prefer to check whether the package is installed))

Yeah, but the last time I checked, Windows 11 production (22000) ISO did have App Installer installed, but that component needed an update for winget to be installed, otherwise before the package was still installed but there was no winget.

AFAIK, production versions don't yet ship with winget built in, so I believe the get-command method is a more forward way to check for it... if that's what you're trying to accomplish here.

**Comment by farag2** [comment]
Hm, may be you're right. I need more tests to do ))

**Comment by pratyakshm** [comment]
Tests related to deployment methods? I'd love to know the results! :)

**Comment by farag2** [comment]
I will keep you noticed. The 6.1 is very clos to the release stage. Just finished testing at 2 am today the most coolest thing the script had since the feature for autocompleating functions names. :)

**Comment by pratyakshm** [comment]
That sounds exciting!
I'm eagerly waiting. :D
