### ISSUE TITLE
[Suggestion] Disable CompatTelRunner

### ISSUE THREAD

**Issue by Obegg** [farag2/Sophia-Script-for-Windows#349]
Why this script doesn't delete/disable this specific telemetry?
(If you don't know what this is you can google "CompatTelRunner.exe". it's found in system32)

Using  .reg (I think)
```
Windows Registry Editor Version 5.00

[-HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\TelemetryController]
```

Using .cmd
```
takeown /F C:\Windows\System32\CompatTelRunner.exe
icacls "C:\Windows\System32\CompatTelRunner.exe" /grant:r Everyone:(OI)(CI)F /T  
icacls "C:\Windows\System32\CompatTelRunner.exe" /grant Users:F
del /F C:\Windows\System32\CompatTelRunner.exe
```

I would love to see this deleted using this script

**Comment by Obegg** [comment]
It's perfectly fine to remove ```CompatTelRunner```, google it, and here are some answers:
https://answers.microsoft.com/en-us/windows/forum/all/how-to-stop-the-windows-compatability-telemetry/3e6f469a-e527-4744-a313-cb52030b3461
https://www.thewindowsclub.com/what-is-compattelrunner-exe-on-windows-10

Regarding the method used (`takeown` or `icacls`) it up to you to decide what to use since there are multiple ways to solve this issue.

**Comment by farag2** [comment]
I'd answer that the problem isn't in methods but the sense of disabling telemetry. It's not our enemy, as many think. Why all try to disable it and after few years blame Windows that it's not stable as they eant it to be, why it looks like not as XP, they got used to, etc. My manifest: stop making it harm, just use it! Especially z if. You low to use such specific commands.
