### ISSUE TITLE
[Suggestion] Add option  tabbed interface and Updated NavBar for build win11 22621.160

### ISSUE THREAD

**Issue by pcwizard7** [farag2/Sophia-Script-for-Windows#351]
### Prerequisites

- [ ] Verify that this is not a Windows issue;
- [ ] Refer to the [**Before running**](https://github.com/farag2/Sophia-Script-for-Windows#fire-before-running-fire).
- [ ] Refer to the [**How to use**](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use).
- [ ] If you issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

In the latest build, Win11 22h2 build 22621.160 allows you to enable the new tabbed interface and updated navbar.

Could this be intergraded to the Sophia script or on demand tweak app as an option to enable/disable these things 

Here are the instructions on how to enable it manually 
https://thecommunity.ru/microsoft/windows/windows11/9386-instrukcija-vkljuchaem-vkladochnyj-interfejs-v-provodnike-v-windows-11-build-25136-dev.html

**Comment by farag2** [comment]
Привет. То есть предлагаешь добавить vivetool? :) Ты серьезно? ))

**Comment by pcwizard7** [comment]
no, just the ability to enable the new windows features

**Comment by pcwizard7** [comment]
Ok understand, thank you.

**Comment by farag2** [comment]
This is great to hear. Believe me: if there is a cool feature, I will add it first. The feature your suggested is a temp solution unfortunately that relies on a 3rd party tool
