### ISSUE TITLE
Checksum incorrect for v5.12.12

### ISSUE THREAD

**Issue by Vitamoon** [farag2/Sophia-Script-for-Windows#352]
Expected checksum `9F8B2A88277186876486DE497BBBBE493F8CD8A51DA09DE39ED46E527BB40096` but got a file with `98534D20748421CA89D78C83EB8B7E1690F0C7A00F4D8A14F2558AC8ACD07B29`
Have redownloaded multiple times

**Comment by farag2** [comment]
Hi. The correct SHA hash sum is in the auto-generated SHA256SUM file. Check it

**Comment by farag2** [comment]
Corrected.
