### ISSUE TITLE
AppsLanguageSwitch: Changes more settings than it should?

### ISSUE THREAD

**Issue by rfgamaral** [farag2/Sophia-Script-for-Windows#363]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [**Before running**](https://github.com/farag2/Sophia-Script-for-Windows#fire-before-running-fire).
- [X] Refer to the [**How to use**](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use).
- [X] If you issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

Hi there,

It doesn't matter if I invoked the script with `AppsLanguageSwitch -Enable` or `AppsLanguageSwitch -Disable`, but this tweaks changes both of these options:

![image](https://user-images.githubusercontent.com/96476/179315013-f90de930-8f03-4d1f-9adc-f62c61756485.png)

But it should only change the first one, right?

This is a screenshot from Windows 10 (where I'm posting this), but I'm reporting this issue from a Windows 11 perspective, where I've actually used and experienced this issue while setting up a new machine with Windows 11.

**Comment by farag2** [comment]
Hm... 🌵

**Comment by farag2** [comment]
Couldn't reproduce: all work correctly. The function uses this cmdlet `Set-WinLanguageBarOption -UseLegacySwitchMode`. Works as it was intended to be.
It doesn't check `Use the desktop language bar when it\s available`.

<https://docs.microsoft.com/en-us/powershell/module/international/set-winlanguagebaroption>

**Comment by rfgamaral** [comment]
@farag2 It does for me, every time, with `-Enable` or `-Disable`. Anything I can do to help debug this?

**Comment by farag2** [comment]
I'd take a look remotely. Really it's so strange... As I mentioned, we may do it via AnyDesk. PM in Telegram: https://t.me/sanctuary_d
