### ISSUE TITLE
NetworkAdaptersSavePower: Prevented the script from running til the end

### ISSUE THREAD

**Issue by rfgamaral** [farag2/Sophia-Script-for-Windows#364]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [**Before running**](https://github.com/farag2/Sophia-Script-for-Windows#fire-before-running-fire).
- [X] Refer to the [**How to use**](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use).
- [X] If you issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

Hi there,

I'm setting up a new machine with Windows 11, and before I did anything else, I wanted to run Sophia Script on it. I've downloaded the latest version, commented/uncommented the appropriate lines, and then ran the script.

The script started to run without issues, but somewhere in the middle of the process, it didn't progress any further, it looked like it was "paused" or something. To debug this issue, I commented every tweak from the start, and uncommented one by one, until the script "paused" again. I realized that `NetworkAdaptersSavePower -Disable` was the tweak causing the issue.

I restored the script to the default, and only commented out `NetworkAdaptersSavePower -Disable`, and since the `-Enable` version is commented by default, the `NetworkAdaptersSavePower` tweak didn't run. And so, the whole script ran successfully without "pausing", from start to finish, without issues.

**Comment by farag2** [comment]
Never saw if it might cause "pausing". the function is pretty simple. Even if you have not the Internet connection, it will be just skipped. So I ran 1000 time on new machines, VMs — behavior was the same. Could you enable logging for the script run? I drew on logger's help only once, but we may give a try. I bet there is no issue in this function at all. 🐱

**Comment by farag2** [comment]
I may send you this function as a raw code tomorrow. Let see what prevents the script from running.

**Comment by farag2** [comment]
In extreme case you may provide me an access via AnyDesk, if you can. But before, here's the function.

```powershell
if (Get-NetAdapter -Physical | Where-Object -FilterScript {$_.Status -eq "Up"})
{
	$PhysicalAdaptersStatusUp = @((Get-NetAdapter -Physical | Where-Object -FilterScript {$_.Status -eq "Up"}).Name)
}

$Adapters = Get-NetAdapter -Physical | Get-NetAdapterPowerManagement | Where-Object -FilterScript {$_.AllowComputerToTurnOffDevice -ne "Unsupported"}

foreach ($Adapter in $Adapters)
{
	$Adapter.AllowComputerToTurnOffDevice = "Disabled"
	$Adapter | Set-NetAdapterPowerManagement
}

# All network adapters are turned into "Disconnected" for few seconds, so we need to wait a bit to let them up
# Otherwise functions below will indicate that there is no the Internet connection
if ($PhysicalAdaptersStatusUp)
{
	while
	(
		Get-NetAdapter -Physical -Name $PhysicalAdaptersStatusUp | ForEach-Object -Process {$_.Status -eq "Disconnected"}
	)
	{
			Start-Sleep -Seconds 2
	}
}
```

**Comment by farag2** [comment]
https://t.me/sanctuary_d

**Comment by farag2** [comment]
Well...
