### ISSUE TITLE
Still Breaking on DeliveryOptimization

### ISSUE THREAD

**Issue by TheSQLGuru** [farag2/Sophia-Script-for-Windows#372]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [**Before running**](https://github.com/farag2/Sophia-Script-for-Windows#fire-before-running-fire).
- [X] Refer to the [**How to use**](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use).
- [X] If you issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

That call produced error logs like below in both 6.1.1 and 6.1.2:

======================================================
.
.
.
EnableLinkedConnections : 1
PSPath                  : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVers
                          ion\Policies\System
PSParentPath            : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVers
                          ion\Policies
PSChildName             : System
PSDrive                 : HKLM
PSProvider              : Microsoft.PowerShell.Core\Registry

DownloadMode : 0
PSPath       : Microsoft.PowerShell.Core\Registry::HKEY_USERS\S-1-5-20\SOFTWARE\Microsoft\Windows\CurrentVersion\Delive
               ryOptimization\Settings
PSParentPath : Microsoft.PowerShell.Core\Registry::HKEY_USERS\S-1-5-20\SOFTWARE\Microsoft\Windows\CurrentVersion\Delive
               ryOptimization
PSChildName  : Settings
PSProvider   : Microsoft.PowerShell.Core\Registry

Deleting...
**********************
Command start time: 20220716185211
**********************
PS C:\Program Files\UTILITIES\Sophia Script for Windows 11 v6.1.1> TerminatingError(Invoke-CimMethod): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: A general error occurred that is not covered by a more specific error code."
>> TerminatingError(Invoke-CimMethod): "A general error occurred that is not covered by a more specific error code."
>> TerminatingError(Invoke-CimMethod): "A general error occurred that is not covered by a more specific error code."
>> TerminatingError(Invoke-CimMethod): "A general error occurred that is not covered by a more specific error code."
>> TerminatingError(Invoke-CimMethod): "A general error occurred that is not covered by a more specific error code."
A general error occurred that is not covered by a more specific error code.
Invoke-CimMethod : A general error occurred that is not covered by a more specific error code.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\DeliveryOptimization\DeliveryOptimizationSettings.psm1:178
char:13
+             Invoke-CimMethod -Namespace $global:DONamespace -ClassNam ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (root/Microsoft/...ptimizationFile:String) [Invoke-CimMethod], CimE
   xception
    + FullyQualifiedErrorId : HRESULT 0x80070422,Microsoft.Management.Infrastructure.CimCmdlets.InvokeCimMethodCommand

======================================================

When I did the following to my sophia.ps1 file, I was able to proceed through to the end of my script:

.
.
.
AdminApprovalMode -Default
MappedDrivesAppElevatedAccess -Enable
#KGB: DeliveryOptimization -Disable
WaitNetworkStartup -Disable
WindowsManageDefaultPrinter -Disable
.
.
.

&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&

I will note that I have been up for almost 30 hours, so everything above could be suspect. :-) I tried to do some more troubleshooting for you, but just couldn't manage it. 

BTW, I REALLY REALLY REALLY appreciate all the efforts you have put into this suite of tooling to help out your fellow techies!! It is especially nice to have the Function file dot-sourced.  If you have a means fans to provide you some contribution please let me know.

**Comment by farag2** [comment]
If you have any errors regrading CIM commands this means that your PowerShell is broken. Very simple. So I really do not know hotw to fix it. Only you have to recall what you made to the OS. ;)
If I were you, I'd start with this

https://github.com/farag2/Utilities/blob/52395d81bec920ca5ae53299240bb269d923411e/Other.ps1#L514

and then with this

https://github.com/farag2/Utilities/blob/52395d81bec920ca5ae53299240bb269d923411e/Other.ps1#L525

**Comment by farag2** [comment]
I'd suggest to reinstall OS from the scratch using an original June, 2022 ISO, but you will think that Im out of my mind. 😹

**Comment by farag2** [comment]
Also you may try with PS 7, but I bet the result will be the same. So thr circle has been ended: built-in PowerShell is broken...

**Comment by farag2** [comment]
I may take a look remotely at you problem via AnyDesk. PM at https://t.me/sanctuary_d

**Comment by TheSQLGuru** [comment]
Thanks for the quick follow-up! Sadly it will be a while before I can circle around to that particular machine, with it's apparently very special build of Powershell. :-D When I do I will try out PSv7 to see if that gives the same error. I will also attempt some debugging to see if it is a bug in that PS call, in which case I will throw it over the wall to the PS team at Microsoft. For now, I just did what that function does manually. 

Oh, I do find it odd that the folder says v1.0 on the Win 11 OS. I thought Win 10 and 11 came installed with much newer versions of PS.

**Comment by farag2** [comment]
> I thought Win 10 and 11 came installed with much newer versions of PS.

This is just a fodler name. The built-in PS version since Windows 10 is 5.0. Then it was upgraded up to 5.1. Windows 11 comes with 5.1 too. MS has no plans for shipping PS 7.x as a default PowerShell version in near future. They told it many times. TThe functionality of PS 7.x is still limited comparing with his predecessor, 5.1.

**Comment by farag2** [comment]
Run this

```powershell
Get-CimInstance -Namespace root/Microsoft/Windows/DeliveryOptimization -ClassName MSFT_DeliveryOptimizationFile
```
