### ISSUE TITLE
DefaultTerminalApp -WindowsTerminal breaks powershell terminal

### ISSUE THREAD

**Issue by soredake** [farag2/Sophia-Script-for-Windows#373]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [**Before running**](https://github.com/farag2/Sophia-Script-for-Windows#fire-before-running-fire).
- [X] Refer to the [**How to use**](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use).
- [ ] If you issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

After doing `.\Sophia.ps1 -Functions "DefaultTerminalApp -WindowsTerminal"` in Windows 11 Pro and rebooting i get this error with powershell and pwsh:
![Снимок экрана 2022-07-19 184648](https://user-images.githubusercontent.com/5204968/179794947-8a0cd7e6-d730-42f9-a2a8-4de40c911583.png)

log:
[log.txt](https://github.com/farag2/Sophia-Script-for-Windows/files/9142744/log.txt)

**Comment by farag2** [comment]
Хм...

**Comment by farag2** [comment]
Несвязанные вещи, но какой стоит антивирус? В логе ошибка про него.

**Comment by soredake** [comment]
Никакой, это виртуалка, defender отключён.

**Comment by farag2** [comment]
Чем отключен?

**Comment by soredake** [comment]
Defender Control 2.1

**Comment by farag2** [comment]
М-да... Ну, я проверил: что и требовалаось доказать: ключи создаются верно, и все отрабатывается правильно без ошибок прямо из Терминала. Как на виртуалке, так и на реальной машине. Опять же несвязанные вещи, но зачем сначала ломать ОС целенаправленно, а потом удивляться ошибкам?
Если хочешь, могу глянуть удаленно через AnyDesk.

**Comment by soredake** [comment]
1) Включив обратно защитник ничего не поменялось, та же ошибка
2) Отключение защитника ничего не ломает, только лишает меня головных болей от его наличия
3) Поменяв эту настройку через интерфейс такой ошибки не наблюдается

Так что....

**Comment by farag2** [comment]
Ну, со мной вести дискуссию по поводу целесообразности применения такого рода программ бессмысленно — я вам не разработчик Win 10 Tweaker. Проверять будем или нет? Так как в коде все верно, и у всех все работает.

**Comment by farag2** [comment]
Время есть после 23 вечера сегодня по Москве.

**Comment by farag2** [comment]
Если будет желание, пиши, пожалуйста, в группу: https://t.me/sophia_chat
Сама понимаешь, что тут не чат, да и иностранцы не поймут, увидя русскую речь ))

**Comment by farag2** [comment]
Ничего себе ты issue пооткрывала — больше 500! 👻

**Comment by soredake** [comment]
For the record, some program(or dependency it installed) i installed was causing this, not sure which.
