### ISSUE TITLE
App not running

### ISSUE THREAD

**Issue by truefriend-cz** [farag2/Sophia-Script-for-Windows#379]
### Prerequisites

- [ ] Verify that this is not a Windows issue;
- [ ] Refer to the [**Before running**](https://github.com/farag2/Sophia-Script-for-Windows#fire-before-running-fire).
- [ ] Refer to the [**How to use**](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use).
- [ ] If you issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

After running script from PowerShel version 7.2 ended error:
```
PropertyNotFoundException: The property 'productState' cannot be found on this object. Verify that the property exists.

MethodInvocationException: Exception calling "Substring" with "2" argument(s): "startIndex cannot be larger than length of string. (Parameter
'startIndex')"

PropertyNotFoundException: The property 'ProductStatus' cannot be found on this object. Verify that the property exists.

```

**Comment by farag2** [comment]
Please run this and the output:

```powershell
Get-CimInstance -Namespace root/SecurityCenter2 -ClassName Antivirusproduct
```

And you didn't check all necessary checkboxes in your issue.

**Comment by truefriend-cz** [comment]
> Please run this and the output:
> 
> ```powershell
> Get-CimInstance -Namespace root/SecurityCenter2 -ClassName Antivirusproduct
> ```
> 
> And you didn't check all necessary checkboxes in your issue.

displayName              : McAfee VirusScan Enterprise
instanceGuid             : {A37DD4B2-BDFF-70DA-DE19-9F9927D6940F}
pathToSignedProductExe   : C:\Program Files (x86)\McAfee\VirusScan Enterprise\SHSTAT.EXE
pathToSignedReportingExe : C:\Program Files (x86)\McAfee\VirusScan Enterprise\VsTskMgr.exe
productState             : 397312
timestamp                : Fri, 12 Aug 2022 08:43:24 GMT
PSComputerName           :

**Comment by farag2** [comment]
Could you format the output to amek it releasable?

```
Code
```

**Comment by farag2** [comment]
And you still didn't check checkboxes that indicates that this is not Windows issue and so on

**Comment by truefriend-cz** [comment]
I have Windows Enterprise G edition where is Windows Defender fully deactivated from factory.

**Comment by farag2** [comment]
Ah, I forgot about it. He-he! Well, this version isn't supported officially, but I will add formal support. Will release a new build today or tomorrow.

**Comment by farag2** [comment]
Fixed in 5.13.4 now.

![изображение](https://user-images.githubusercontent.com/10544660/184406413-3b6190f8-bfe0-41ce-b299-1b7576f6ca13.png)

All these errors are minor and can be ignored. I do not not want to re-write all the script only for this special Chinese Windows. :)

**Comment by truefriend-cz** [comment]
Sorry but issue is not fixed...
after run ended with error:
```
The property 'productState' cannot be found on this object. Verify that the property exists.
At U:\Downloads\T\Module\Sophia.psm1:285 char:2
+     $productState = (Get-CimInstance -Namespace root/SecurityCenter2  ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

Exception calling "Substring" with "2" argument(s): "startIndex cannot be larger than length of string.
Parameter name: startIndex"
At U:\Downloads\T\Module\Sophia.psm1:286 char:2
+     $DefenderState = ('0x{0:x}' -f $productState).Substring(3, 2)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentOutOfRangeException

The property 'ProductStatus' cannot be found on this object. Verify that the property exists.
At U:\Downloads\T\Module\Sophia.psm1:327 char:6
+     if ((Get-CimInstance -ClassName MSFT_MpComputerStatus -Namespace  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict
```

**Comment by farag2** [comment]
I tested it on a VM. Could you redownload archive again? I uploaded a new version with the same tag. And upload screenshot with the error.

**Comment by farag2** [comment]
And please t3at without the Wrapper.

**Comment by farag2** [comment]
If you have Discord: upload screenshots there.
https://discord.gg/sSryhaEv79

**Comment by truefriend-cz** [comment]
![image](https://user-images.githubusercontent.com/7845691/184507949-0b6d5aff-c1cf-4469-8d92-a4736caa7771.png)
on left is PS 5.1, left PS 7.2

**Comment by truefriend-cz** [comment]
> If you have Discord: upload screenshots there. https://discord.gg/sSryhaEv79

i will accepted... i am send screenshot to channel sophia-script-en

**Comment by farag2** [comment]
> ![image](https://user-images.githubusercontent.com/7845691/184507949-0b6d5aff-c1cf-4469-8d92-a4736caa7771.png) on right is PS 5.1, left PS 7.2

The left screenshot makes no sense: you tried to run the PS 5.1 module in PS 7 instance.))

**Comment by farag2** [comment]
And run this

```powershell
Get-ItemPropertyValue -Path "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion" -Name EditionID
```

**Comment by truefriend-cz** [comment]
> And run this
> 
> ```powershell
> Get-ItemPropertyValue -Path "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion" -Name EditionID
> ```

`EnterpriseG`

**Comment by truefriend-cz** [comment]
> > ![image](https://user-images.githubusercontent.com/7845691/184507949-0b6d5aff-c1cf-4469-8d92-a4736caa7771.png) on right is PS 5.1, left PS 7.2
> 
> The left screenshot makes no sense: you tried to run the PS 5.1 module in PS 7 instance.))

yes, but in Sophia script is...
```
#Requires -RunAsAdministrator
#Requires -Version 5.1
```

**Comment by farag2** [comment]
Waiting for your response on Discord.

**Comment by farag2** [comment]
Any response?
