### ISSUE TITLE
AppsLanguageSwitch - wrapper wrong description.

### ISSUE THREAD

**Issue by TristisOris** [farag2/Sophia-Script-for-Windows#389]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [X] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

option works opposite than description say.
Wrapper v2.5.7

### Windows Version

21h2 19044.1949

### Sophia Script version

v5.13.4

**Comment by farag2** [comment]
Which option?..

**Comment by farag2** [comment]
@BenchTweakGaming

**Comment by farag2** [comment]
Yeah, really. Fixed locally. Thanks.
