### ISSUE TITLE
[Bug] High RAM Usage - HEIF -Install

### ISSUE THREAD

**Issue by Obegg** [farag2/Sophia-Script-for-Windows#391]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [X] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

HEIF -Install

### Windows Version

Windows 10 Pro 21H2 19044.2006

### Sophia Script version

5.13.4

**Comment by farag2** [comment]
What's the problem? :) This function just downloads [this](https://github.com/farag2/Sophia-Script-for-Windows/blob/master/AppX/Microsoft.HEVCVideoExtension_2.0.51121.0_x64__8wekyb3d8bbwe.Appx) file and run `Add-AppxPackage -Path "path\to\Microsoft.HEVCVideoExtension_2.0.51121.0_x64__8wekyb3d8bbwe.Appx" -Verbose`

**Comment by Obegg** [comment]
The problem is that it reaches 10% and keeps going, it doesn't finish, which results in high RAM usage, over 5GB, until I manually close PowerShell.

**Comment by farag2** [comment]
It really occurs only on your system. We never seen it before. And cannot be fixed. Probably, something wrong with your system?

**Comment by Obegg** [comment]
I don't think there's any issue with my system, it's stable, no blue screens, it's not my first time running this script and it a weird issue that never occurred before. but as I said - once I disable this function the issue resolved.

**Comment by farag2** [comment]
That's a pitty, but I cannot fix how packages are installed. :(
So this is very weird thing.

**Comment by Myhdd201** [comment]
if you have any antivirus installed, please disable it for a while.

**Comment by farag2** [comment]
> if you have any antivirus installed, please disable it for a while.

Probably, you're right. If we are talking about 3rd party shitty AVs like Avira.

**Comment by Obegg** [comment]
ESET

**Comment by Myhdd201** [comment]
always some missy takes from AV.
