### ISSUE TITLE
New Win 11 Home 21H2 PC won't run wrapper 2.5.7 ?  @BenchTweakGaming - yes ran as admin

### ISSUE THREAD

**Issue by FredTTya** [farag2/Sophia-Script-for-Windows#393]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [X] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

Tried to run today's version & the previous one to no avail...
![InitialError](https://user-images.githubusercontent.com/80644669/194779085-80597600-b49a-48c9-87af-ba074c4ff2c8.png)
![SystemInfo](https://user-images.githubusercontent.com/80644669/194779087-48389a6e-b8ba-4bc5-b70f-6446ca17ad71.png)

### Windows Version

Windows 11 21H2 Home 22000.1042

### Sophia Script version

6.14 & 6.15

**Comment by farag2** [comment]
Hi. No, the Wrapper supports any modern Windows 10 & 11. Could you take a screenshot when you launch the app? Such errors may occur only if you try to run x64 app on a Windows x86, but Windows 11 doesn't provide such version. This is puzzling me...

**Comment by farag2** [comment]
Yeah, really the exe was corrupted. Just how? Re-uploaded it and push compiling. It will be done in few minutes: https://github.com/farag2/Sophia-Script-for-Windows/actions/runs/3215571084/jobs/5256762670

Thank you!

**Comment by farag2** [comment]
Please, test: https://github.com/farag2/Sophia-Script-for-Windows/releases/tag/6.1.5

**Comment by FredTTya** [comment]
Thank you I'll try it again

**Comment by FredTTya** [comment]
Ok, now the wrapper opens but I can't make any selections??  They are all
full blue boxes that don't react to any mouse or keyboard??

**Comment by FredTTya** [comment]
Scratch that, my bad...  It works thank you again

**Comment by farag2** [comment]
Did you import your preset file? For me it works fine. By default UI is disable waiting for a preset to be imported.
Anyway, let's proceed tomorrow: it's 1 am for me. :)
