### ISSUE TITLE
LTSC.2021.5.13.5 Not executing / errors.  

### ISSUE THREAD

**Issue by Brierith** [farag2/Sophia-Script-for-Windows#395]
### Prerequisites

- [x] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [X] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

Upon running the script, it throws a variety of errors for all of the functions, and it ends up not executing at least one.  please refer to the image below. 

![Capture](https://user-images.githubusercontent.com/81455201/194904520-ef5cf982-877d-4fcf-96a9-bbb81249e7ee.PNG)

### Windows Version

Windows 10 21H2 Enterprise LTSC 19044.2075

### Sophia Script version

LTSC.2021.5.13.5

**Comment by farag2** [comment]
Oh, I think, I didn't close brackets...

**Comment by Brierith** [comment]
There's also error with regards to CommandNotFoundException, for the functions below it.  I could submit the entire returns of the shell if that helps.

**Comment by farag2** [comment]
The error below is normal for PoweShell. It throws an error that you must restart powershell.exe. Will re-upload fixed archives in an hour. ;(

**Comment by farag2** [comment]
Done. Please, test.
https://github.com/farag2/Sophia-Script-for-Windows/releases/tag/6.1.5

**Comment by Brierith** [comment]
Tested, here's the output. 
Does not seem to pass the OS check?.
![1](https://user-images.githubusercontent.com/81455201/194920115-34fec187-647a-4a07-8ed7-3585de5e539e.PNG)

**Comment by farag2** [comment]
What's your Windows version? It seems, you're trying to run a wrong script version. The red error is OK.

**Comment by Brierith** [comment]
Windows 10 Enterprise IoT. Additional info, previous versions of your scripts works with no issues. 
![image](https://user-images.githubusercontent.com/81455201/194920474-f5f33447-86ef-42e2-9a4d-8b90cd4a59e0.png)

**Comment by farag2** [comment]
IoT Ent LTSC ≠ LTSC 2021 )). Please, an ordinary Windows 10 version. And I'm curious what Edition do you have:
```powershell
(Get-WindowsEdition -Online).Edition
```

**Comment by farag2** [comment]
Good. You change `-eq` to `-match` on the 71th string in the `Sophia.psm1` file. Will you figure out?)

**Comment by Brierith** [comment]
Yup, got that from here, thanks for the clue 😄.

**Comment by farag2** [comment]
Edited in my code too. Working on 6.2 now. :)
