### ISSUE TITLE
Small red text

### ISSUE THREAD

**Issue by Hellements** [farag2/Sophia-Script-for-Windows#406]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [ ] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

I just clicked to run the script.
![error](https://user-images.githubusercontent.com/88634350/199011372-49da0ebc-42de-44bc-9125-2e935214732d.jpg)

### Windows Version

Windows 10 Pro 21H2 19044.2130

### Sophia Script version

Sophia_Script_for_Windows_10_v5.14.1

**Comment by farag2** [comment]
Hm, good issue. thanks!

**Comment by farag2** [comment]
Have you appreciated a new task for making policies visible in gpedit.msc? 😸

**Comment by Hellements** [comment]
Yes friend, thank you for everything you're sharing here with us, all your effort and hardworking. We appreciate it very much. :)

**Comment by farag2** [comment]
Fixed!

**Comment by farag2** [comment]
https://github.com/farag2/Sophia-Script-for-Windows/blob/e03d3871ed89ad6dfbeb6708c0a341b2f1d5321d/src/Sophia_Script_for_Windows_10/Module/Sophia.psm1#L10745
