### ISSUE TITLE
PowerShell Core does not have -Encoding Byte

### ISSUE THREAD

**Issue by zimmersi** [farag2/Sophia-Script-for-Windows#410]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [ ] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

Sophia -Functions UnpinAllStartApps

### Windows Version

Windows 11 Pro 22H2 22621.675

### Sophia Script version

6.2.3

**Comment by zimmersi** [comment]
"-Encoding Byte" is replaced by "-AsByteStream"

**Comment by farag2** [comment]
Thanks a lot!
