### ISSUE TITLE
Script hangs on 1 out of 3 similar laptops

### ISSUE THREAD

**Issue by FredTTya** [farag2/Sophia-Script-for-Windows#418]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [ ] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

![ScriptHangsHere](https://user-images.githubusercontent.com/80644669/205834274-54612856-f2aa-4c68-ac94-2e1d8b1bb911.png)

### Windows Version

Windows 11 Pro 22H2 22621.900

### Sophia Script version

6.2.3 & 6.2.4

**Comment by farag2** [comment]
Hi. It doesn't hang. Probably, it takes too much time to scan all your reg keys. How long did you wait?

**Comment by farag2** [comment]
Also sometimes PowerShell console hangs and you have to send any key to it from keyboard. it cannot be bypassed unfortunately. Do you still face the issue?

**Comment by FredTTya** [comment]
I tried sending any key to PS but that didn't work.  So I restarted the
script, watched it hang for about an hour then left it running over night.
When I woke it had completed???

**Comment by farag2** [comment]
could you provide me a remote access to see the bug? I've never faced it before. PM me in Telegram: https://t.me/sanctuary_d

**Comment by FredTTya** [comment]
It's a new Lenovo laptop I delievered to a client yesterday.  It would be
complicated at the his point.

**Comment by farag2** [comment]
Well, actually, this is not a necessary function to apply. So sleep well )). Anyway, this is strange that it took you so much time. As for me it takes about 5 minutes because it scans 4 reg paths recursively.

**Comment by FredTTya** [comment]
Thank you...  believe me, I would like to know as well.  Maybe we can work
something out next week?

**Comment by farag2** [comment]
I'm always free. PM me and we will schedule everything 😸
