### ISSUE TITLE
Script stuck without any error

### ISSUE THREAD

**Issue by TristisOris** [farag2/Sophia-Script-for-Windows#438]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [ ] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

stuck with any switcher option - none, disable, enable. AD admin account, works before on local admin.

![image](https://user-images.githubusercontent.com/1270117/211849767-6d4dfd3c-0e31-450f-a7eb-8559b484bcc2.png)

### Windows Version

Win11 22H2 22621.1105

### Sophia Script version

6.2.7

**Comment by farag2** [comment]
Are you using 5.13.4 version? it's very outdated. how could run 6.2.7 with that old windows? I have no idea. Please download the latest version, 6.2.7 if you're using Windows 11.

**Comment by farag2** [comment]
https://github.com/farag2/Sophia-Script-for-Windows/releases/latest

**Comment by TristisOris** [comment]
got it. That was my old win10 config. Don't now it can be outdated.
it works now, thanks.

**Comment by farag2** [comment]
He-he. Now you're officially hacker. 🐱
