### ISSUE TITLE
request for setting - Prefer IPv4 over IPv6

### ISSUE THREAD

**Issue by TristisOris** [farag2/Sophia-Script-for-Windows#440]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [ ] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

script can only enable\disable ipv6.
But official recomendation is "Prefer IPv4 over IPv6" instead . https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/configure-ipv6-in-windows
since a lot things linked to ipv6 service.

so that about both win10+win11.

### Windows Version

win11

### Sophia Script version

11_v6.2.7

**Comment by farag2** [comment]
Hi. This is not actually an issue. Script only provides feature to disable not, it doesn't make users to do it. So everyone can just comment out this function.

**Comment by TristisOris** [comment]
as i say it request, why this option have only 2 options instead of best possible?

**Comment by farag2** [comment]
You meant, y

**Comment by farag2** [comment]
@TristisOris, https://github.com/farag2/Sophia-Script-for-Windows/releases/tag/6.3.0
