### ISSUE TITLE
Doesn't remove apps

### ISSUE THREAD

**Issue by Klmileca** [farag2/Sophia-Script-for-Windows#447]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [ ] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

I have run the current version of this script on 2 different computers that are new setups. Windows was updated to correct version and on both computers the script did not remove any apps that I selected to uninstall for all users. After rebooting the computer, all apps that were selected, were not removed. 

### Windows Version

Windows 10 22H2

### Sophia Script version

15.5.0

**Comment by farag2** [comment]
This is very strange. The script does work. I used it by myself yesterday. Could I have a look the issue remotely via AnyDesk?

**Comment by farag2** [comment]
> 15.5.0

5.5.0?

**Comment by Klmileca** [comment]
Yes when would you like to do this?

**Comment by Klmileca** [comment]
I was using Sophia_Script_for_Windows_10_v5.15.0

**Comment by farag2** [comment]
I will available tomorrow after 20 PM MSK timze zone. Ping me in Discord: sanctuary_s#6351

**Comment by Klmileca** [comment]
That won't work for me. This is a computer at work and I am only available
here M-F from 6:30am - 3:30pm. is there a file or something I can send you?

**Comment by Klmileca** [comment]
M-F from 6:30am - 3:30pm  that is EST...

**Comment by farag2** [comment]
Send all files as archive I will check it

**Comment by farag2** [comment]
Just make a zip archive of all script files

**Comment by Klmileca** [comment]
[Sophia_Script_for_Windows_10_v5.15.0.zip](https://github.com/farag2/Sophia-Script-for-Windows/files/10581609/Sophia_Script_for_Windows_10_v5.15.0.zip)

**Comment by farag2** [comment]
I will check...

**Comment by farag2** [comment]
I checked. Everything works like a charm. 

> M-F from 6:30am - 3:30pm that is EST...

So, I'm available tomorrow. Ping while you're at your work. this is OK for me.

**Comment by farag2** [comment]
I'm free...

**Comment by farag2** [comment]
Well...
