### ISSUE TITLE
PropertyNotFoundException: CurrentBuild cannot be found on this object.

### ISSUE THREAD

**Issue by sgeraldes** [farag2/Sophia-Script-for-Windows#449]
I'm trying to run Sophia on a brand new Windows installation. Windows 11, up-to-date. Current Build is yesterday's. 
The error is:
PropertyNotFoundException: The property 'CurrentBuild' cannot be found on this object. Verify that the property exists.

Full text:

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     6.3.1                 Sophia                              {ActiveHours, AdminApprovalMode, AdvertisingID, A…
PropertyNotFoundException: The property 'CurrentBuild' cannot be found on this object. Verify that the property exists.

RegistrationState           : 3
ServiceID                   : 7971f918-a847-4430-9279-4a52d1efe18d
IsPendingRegistrationWithAU : False
Service                     : System.__ComObject

ReturnValue    : 0
PSComputerName :

**Comment by farag2** [comment]
Also, you didn't fill in the issue template properly...

**Comment by sgeraldes** [comment]
Sorry, I'm not sure what the template is like. I didn't get one to complete when filling out the issue. I just took this one from the other open issue.

Prerequisites

- [x]     Verify that this is not a Windows issue;
- [x]     Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [x]     Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [x]     I do not use a homebrew Windows image;
- [x]     I did not tweak Windows before that could cause system instability;
- [ ]     If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue


Steps to reproduce

Not sure how to reproduce as this is a brand-new installation. Other than re-installing and taking note of the installation steps and post-instalation configuration:
- Installing drivers (NVidia, logitech g hub, logitech camera settings, stream deck app, chocolatey for package distribution, firefox through choco, battle.net -choco, powershell -choco, runtimes -choco).
- basic configuration: moving taskbar buttons to right, dark mode, and setting monitors (i have 3) one of them in portrait.

Windows Version

Windows 11 Pro 22H2 Windows Feature Experience Pack 1000.22634.1000.0

Sophia Script version
6.3.1

**Comment by farag2** [comment]
Could upload a screenshot with the error?

**Comment by sgeraldes** [comment]
![image](https://user-images.githubusercontent.com/14790771/217684158-cf0b006f-74c0-444c-8287-2c450345814c.png)

**Comment by farag2** [comment]
Very strange. Could I have a look remotely via AnyDesk? Ping me please in Telegram: https://t.me/sanctuary_d or Discord sanctuary_s#6351

**Comment by sgeraldes** [comment]
I finally formated and reinstalled windows.
Twice. The first time I got the same result, so I recreated the usb drive
with the windows media download tool.
After formating again, I disconnected the pc and did an offline install of
win11.
I tried again, no luck, same error. However I got it connected, updated
windows, and after three reboots, it worked.
Maybe there was something bad with the specific version the usb drive was
loaded before. I think it was originally 21H2.
So hopefully, this is not back anytime soon.


Kust for fun, I also tried with Tiny11, an streamlined small win11 version
that's on the news lately. It had the same error result as the OP. Just
saying so that people don't try it if you are expecting it to work with
this version.

**Comment by farag2** [comment]
Ah, I found the error cause. This is my fault. By anyway, you had to view a notification about your Windows is older than the script supports. So just update your Windows by installing all updates (all means even hidden ones). That's all. Soon I will make a fox commit.

**Comment by farag2** [comment]
> I think it was originally 21H2.

Windows 11 22H2 already exists))

**Comment by farag2** [comment]
I fixed it. Just copy new module version manually and paste it. I've not released it yet as a separate archive.

https://github.com/farag2/Sophia-Script-for-Windows/blob/master/src/Sophia_Script_for_Windows_11_PowerShell_7/Module/Sophia.psm1

**Comment by sgeraldes** [comment]
Yes. 22H2 was rhe new usb stick's build.
And yes, I also found that one, and just removed the version checks "fixed"
it, but that would have, maybe, caused other issues, so I put it back.
The extrange thing is that the error popped up as if "CurrentBuild"
property of the Version$ object was not existant, but I could get it from
powershell with no problem.

**Comment by farag2** [comment]
> The extrange thing is that the error popped up as if "CurrentBuild"

Yeah, yeah, I didn't check that property correctly. Ou found a bug. Thanks)) Please check again by replacing the whole module code with a new one.
