### ISSUE TITLE
sophi-script fails on every function

### ISSUE THREAD

**Issue by soredake** [farag2/Sophia-Script-for-Windows#453]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [ ] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

Log:
[sophi-log.txt](https://github.com/farag2/Sophia-Script-for-Windows/files/10807027/sophi-log.txt)

### Windows Version

Windows 11 Pro 22621.1265

### Sophia Script version

6.3.2

**Comment by farag2** [comment]
Please try to copy the whole new module (unreleased yet) and paste into you psm1 file: https://raw.githubusercontent.com/farag2/Sophia-Script-for-Windows/master/src/Sophia_Script_for_Windows_11_PowerShell_7/Module/Sophia.psm1

**Comment by soredake** [comment]
@farag2 now i get this
[sophi-log-2.txt](https://github.com/farag2/Sophia-Script-for-Windows/files/10807389/sophi-log-2.txt)

**Comment by farag2** [comment]
And try again...

**Comment by soredake** [comment]
It works now, thanks!
