### ISSUE TITLE
My xbox app doesn't work now

### ISSUE THREAD

**Issue by Naimer457** [farag2/Sophia-Script-for-Windows#454]
### Prerequisites

- [x] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [X] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

Idk what that means, a friend installed for me the Sophia.ps1 and then i can't play any of my games there

### Windows Version

Windows 11 22H2 22621.1265

### Sophia Script version

11.02.2023

**Comment by Naimer457** [comment]
After a friend did everything for me to set up, I tried to play atomic heart and i got error 0x800700e9 and i can't login anymore to the xbox app

**Comment by farag2** [comment]
Hm... Did you remove Xbox related apps (they're unchecked by default)?

**Comment by farag2** [comment]
PM me in Discord: sanctuary_s#6351
I think I know how to fix it. I need a remote control via AnyDisk.

**Comment by Naimer457** [comment]
request sent
