### ISSUE TITLE
Sophia Script Wrapper 2.6.5 : tooltips are not displayed when hovering the mouse over the label of the fields

### ISSUE THREAD

**Issue by Grimst** [farag2/Sophia-Script-for-Windows#471]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [ ] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

## Step to reproduce :

right-side of the screen : double-click on SophiaScriptWrapper.exe (with admin rights), import Sophia.ps1, mouse over a label field : tooltip diplayed
![Clipboard01](https://user-images.githubusercontent.com/16018842/229069219-9db1c63b-858c-4adf-b5b1-5368fc58603d.jpg)

left-side of the screen : double-click on SophiaScriptWrapper.exe (with admin rights), mouse over a label field : tooltip is not diplayed
![Clipboard02](https://user-images.githubusercontent.com/16018842/229069230-8157969b-c7b7-4fb7-9f53-1dbc584f0fb1.jpg)

Steve

### Windows Version

Windows 10 22h2, build 19045.2728

### Sophia Script version

2.6.5

**Comment by farag2** [comment]
`If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue`

David, do you have answers?) @BenchTweakGaming

**Comment by BenchTweakGaming** [comment]
Hello @Grimst,

ToolTips for Labels should show "mostly" for all labels before you import "Sophia.ps1". The ComboBox, CheckBoxes accompanying the Label should not show ToolTips before importing "Sophia.ps1".

Notice: not all Labels and ComboBox, CheckBoxes have ToolTips. The really unique special controls may not have them. I will fix that later.

I just downloaded Wrapper, 10 and 11 PS5.2 scripts and tested them out on my development computer. Here is a YouTube video I uploaded testing. Am I missing something?

[https://youtu.be/j5DQ9PRIvrg](url)

**Comment by farag2** [comment]
@Grimst, I didn't get what the bug you faced with. By default there are only 3 tooltips to show without importing a preset. After impoting you're able to read all supported tooltips (from JSON file). So I couldn't reproduced your bug: after improting all of them are shown as they should. Probably you can record a video for us?

**Comment by Grimst** [comment]
> @Grimst, I didn't get what the bug you faced with. By default there are only 3 tooltips to show without importing a preset. After impoting you're able to read all supported tooltips (from JSON file). So I couldn't reproduced your bug: after improting all of them are shown as they should. Probably you can record a video for us?

it doesn't work for me, after the import the tooltips don't appear. 3 different tooltips, do you mean different languages?

**Comment by farag2** [comment]
Could I check the bug remotely via AnyDesk?

**Comment by Grimst** [comment]
Ok for me how to proceed ?

**Comment by farag2** [comment]
Discord: sanctuary_s#6351

**Comment by Grimst** [comment]
OK I give up
All this for a small bug that can be easily worked around finally by open two windows side by side. if I'm the only one with this problem and it's OK for everyone, I'll close the issue.

thanks for your time [farag2](https://github.com/farag2) and [BenchTweakGaming](https://github.com/BenchTweakGaming)

have a nice week-end,

Steve
