### ISSUE TITLE
appx is not supported in powershell 7 platform(0x80131539).

### ISSUE THREAD

**Issue by ZilchBloke** [farag2/Sophia-Script-for-Windows#472]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [X] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

AppxPackage module is not working with powershell 7.3.3  
but AppxPackage module was compatible with default poweshell with windows 10.  

Sophia script couldnot remove apps like onenote, spotify, cortana, alarm, phone,xbox, etc.
Sophia script cannot be used with older powershell to use AppxPackage module.

Work around : had to remove app individually using powershell 5 that was default in windows 10 (run as Admin):
For example for windows alarm app :
check using : `Get-AppxPackage -allusers *WindowsAlarm*`  
and then pipe it with `Remove-AppxPackage` like this :  
 `Get-AppxPackage -allusers *windowsalarm* | Remove-AppxPackage`

### Windows Version

Windows 10 22H2 (OS built 19045.2788)

### Sophia Script version

Sophia Script for Windows 10 PowerShell-7-V 5.16.3

**Comment by farag2** [comment]
Hm... let me check. I import the appropriate module for PS 7.

**Comment by farag2** [comment]
Also do you have the error screenshot?

**Comment by ZilchBloke** [comment]
![image](https://user-images.githubusercontent.com/128199827/229285361-464e172f-1430-4aa3-88dd-7561391ef041.png)

**Comment by farag2** [comment]
I got it and found out that accidently removed 2 strings. Please wait.

**Comment by ZilchBloke** [comment]
sure. thanks a lot. you are the best 👍  : )

**Comment by farag2** [comment]
Fixed. Just replaced the whole module with a new one: https://raw.githubusercontent.com/farag2/Sophia-Script-for-Windows/master/src/Sophia_Script_for_Windows_10_PowerShell_7/Module/Sophia.psm1
