### ISSUE TITLE
Script not detecting Disney+ and Spotify Music apps.

### ISSUE THREAD

**Issue by Hellements** [farag2/Sophia-Script-for-Windows#476]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [ ] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

I installed a fresh Windows 10 x64 and then all the updates available. I ran the script and on the window where we can select the apps to remove, it can't find the Disney+ and Spotify Music, making them unable to be uninstalled.

### Windows Version

Windows 10 Pro Version	22H2 OS build	19045.2728

### Sophia Script version

Sophia.Script.for.Windows.10.v5.16.4.zip

**Comment by farag2** [comment]
Because they aren't installed?))

**Comment by Hellements** [comment]
Hello @farag2 
This is strange. Those 2 apps appeared on recent Windows 10 updates. As I said before, I did a fresh install and then all Windows updates. Uninstalled all apps using the script. For some reason, Disney+ and Spotify Music are still showing on add/remove programs and on Start button. I click on them and they run normally. I have to use another uninstaller tool such Revo Uninstaller Pro to properly remove those apps while Sophia can't detect them.
So, have you tried to install Windows 10 latest version with all updates? I see the same happening on english and brazilian variants.
Thanks.

**Comment by farag2** [comment]
PM me in Telegram: @sanctuary_d. I will check remotely the vug via AnyDesk.

**Comment by farag2** [comment]
Well...

**Comment by farag2** [comment]
I've fixed it in `5.16.5`. But this is a dirty trick. The problem that these apps aren't a part of the appx Bundle.
