### ISSUE TITLE
Documentation Update or Wrapper preset import bug (@BenchTweakGaming)

### ISSUE THREAD

**Issue by Amoeba00** [farag2/Sophia-Script-for-Windows#478]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [x] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

Using the wrapper application and importing a preset:  
If the preset is NOT in the default Sophia Script folder (where the default Sophia.ps1 script resides), it won't load and instead generate a message about a new version of Sophia Script being found.

Moving the same script to that default folder, will result in proper preset loading and expected behavior.

Steps to Reproduce:
Start Wrapper - load default preset from sophia folder - (optional: make changes) - export preset to folder outside of the default - load that preset.  
You will then see message about new version and pressing No/Cancel - results with empty preset (yes results in expected browser launch behavior but wrapper still "broken").
Move that same preset to the original default folder and import it.
No issues.

Note:  If it helps, last time I used this was on a Win10 machine with Sophia v5.14.3 and Wrapper v2.5.7 - with no issues importing from different folder.

### Windows Version

Win 11 Pro 22H2 (22621.1555)

### Sophia Script version

6.4.4

**Comment by farag2** [comment]
You cannot move preset to any folder excet the folder where all other files are. Because preset tries to import module from $PSScriptRoot folder.

**Comment by farag2** [comment]
I'm working 6.5.0 already. :)
