### ISSUE TITLE
Possible Bug:  Hang when re-running after changes made.

### ISSUE THREAD

**Issue by Amoeba00** [farag2/Sophia-Script-for-Windows#479]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [X] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

Load preset, run preset, no issues, reboot.
Continue with manual cleanup and other application installs.
Load different, but similar preset, hangs at the GPO section.
Even with running same preset, it hangs.
Thoughts?  Thanks!

![image](https://user-images.githubusercontent.com/39176113/232846247-081c8cf3-076a-4ad0-acc3-466bf452109e.png)

### Windows Version

Win 11 Pro 22H2 (22621.1555)

### Sophia Script version

6.4.4

**Comment by farag2** [comment]
Hi. Actually, it doesn't hang. :) It fully depands on your SSD speed. What may I advise: after 5 minutes press any key (when you focus is in the console window) except Enter. Sometimes PowerShell hangs and we cannot fix it.
The code is very primitive but it takes on modern NVMe SSDs up to 10 minutes to find all necessary reg keys. So wait until the end or press sometimes Space key. :)

**Comment by Amoeba00** [comment]
I let it sit for much longer than that and the first time it runs, when it actually does stuff - it doesn't hang at all.
Additionally, I created a separate local admin user, logged in, and ran the script - hangs at the same spot.
Again - no issues the first time - just the second.

**Comment by farag2** [comment]
Well... Could I see the hang remotely via AnyDesk? Ping me plsnin Telegram: @sanctuary_d

**Comment by Amoeba00** [comment]
Well holy crap - stepped away - came back, and the script did finish.  Thanks for the offer though.  That was very kind of you.  Have a great day!

**Comment by farag2** [comment]
Magic! You too! Thanks for the feed back!

**Comment by Amoeba00** [comment]
Also, just sent you a Kofi donation.

**Comment by Amoeba00** [comment]
Well, anything to support the project!
