### ISSUE TITLE
Support the new Dev Channel with the 23xxx series designation

### ISSUE THREAD

**Issue by w4po** [farag2/Sophia-Script-for-Windows#480]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [X] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

Hello,
Please Add support for the new Dev Channel with the 23xxx series designation.

```
Script     6.4.4      Sophia                              {ActiveHours, AdminApprovalMode, AdvertisingID, AeroShaking...}
WARNING:
Your Windows 11 build: 23430.1000. Supported builds: 22621.1413 and higher. Run Windows Update and try again
```

Thank you.

### Windows Version

Windows 11 Home Insider Preview 22H2 23430.1000

### Sophia Script version

6.4.4

**Comment by farag2** [comment]
Already fixed in 6.50. Not released yet. :)

**Comment by w4po** [comment]
Thank you very much for the awesome support,
Looking forward to it soon <3

**Comment by w4po** [comment]
Hello @farag2,
When is it going to be released or May I have it now?

Thank you.

**Comment by farag2** [comment]
Will upload the updated string this evening. You will need to replace it the existing one.

**Comment by farag2** [comment]
replace this
https://github.com/farag2/Sophia-Script-for-Windows/blob/baf4159b1f282175c425de3734ef4d98a936ebfb/src/Sophia_Script_for_Windows_11/Module/Sophia.psm1#L266
string with this one

```powershell
{($_ -ge 22621) -and ($_ -le 22624)}
```
