### ISSUE TITLE
Sophi Script is downloaded to $PWD when you download it from .ps1 script

### ISSUE THREAD

**Issue by soredake** [farag2/Sophia-Script-for-Windows#482]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [ ] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

1) Create `script.ps1` file with `powershell .\sophi.ps1` content.
2) Create `sophi.ps1` file with `irm script.sophi.app -useb | iex` content.
3) Run `script.ps1`
4) Sophi will be downloaded to $PWD instead of ~/Downloads.

### Windows Version

Windows 11 Pro 22H2 22621.1555

### Sophia Script version

6.4.4

**Comment by farag2** [comment]
This is by design: https://github.com/farag2/Sophia-Script-for-Windows/blob/baf4159b1f282175c425de3734ef4d98a936ebfb/Download_Sophia.ps1#L34

Someone asked me and I check before downloading. Not OK for you?

**Comment by soredake** [comment]
It's a bit confusing that it downloads to $PWD if currently directory is not $HOME or $env:SystemRoot\System32, i've wondered why my script is not working, i called `sudo ~\Downloads\Sophia*\Sophia.ps1 -Function <Function>` in script but to my surprise sophi script was not in downloads (probably current was changed when installing packages from choco/winget).

**Comment by farag2** [comment]
What if I add a new parametr to specifiy the output folder?

```powershell
irm script.sophi.app -useb -Path D:\folder | iex
```

**Comment by farag2** [comment]
Ah, I couldn't...
From now script will always be downloaded to a downloads folder.

https://github.com/farag2/Sophia-Script-for-Windows/commit/f006e0300b2ae458e37ab3d65302b4a900d8c2d0
