### ISSUE TITLE
Wrong translation strings in System - WindowsLatestUpdates description

### ISSUE THREAD

**Issue by schqual** [farag2/Sophia-Script-for-Windows#490]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [X] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

@BenchTweakGaming
Wrapper 2.6.6
WindowsLatestUpdates tooltip has Deutch translation instead of Russian while OS language is set to Russian.
![изображение](https://github.com/farag2/Sophia-Script-for-Windows/assets/82216521/db1a3586-8a43-4a63-bbdf-ed4759be74c1)

Also minor issue - default Wrapper windows size is wider than size of screen (probably because of Edge settings checkboxes).
My laptop's screen resolution is 1920*1080 (recommended) with Scaling 125% (recommended).
![изображение](https://github.com/farag2/Sophia-Script-for-Windows/assets/82216521/a9f8cd55-caa1-4e36-a97c-c9fd8a6c0fd3)

### Windows Version

Windows 11 Pro 22H2 22621.1702

### Sophia Script version

6.5.0

**Comment by farag2** [comment]
Спасибо. :)

**Comment by farag2** [comment]
> Also minor issue - default Wrapper windows size is wider than size of screen (probably because of Edge settings checkboxes).
My laptop's screen resolution is 1920*1080 (recommended) with Scaling 125% (recommended).

@BenchTweakGaming

**Comment by BenchTweakGaming** [comment]
Window sized changed by changing length size of Checkboxes for PreventEdgeShortcutCreation function - fixed for next update v2.6.7
