### ISSUE TITLE
feature request: add option to prevent teams installation

### ISSUE THREAD

**Issue by soredake** [farag2/Sophia-Script-for-Windows#491]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [ ] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

It would be nice if sophiscript had option to prevent teams installation https://woshub.com/remove-teams-chat-windows/ https://www.outsidethebox.ms/21375/

The problem is "ConfigureChatAutoInstall" registry key needs to be added with TrustedInstaller rights.

### Windows Version

Windows 11 Pro

### Sophia Script version

6.5.0

**Comment by farag2** [comment]
Что, реально от TI надо создать ключ? :)
