### ISSUE TITLE
Reinstalls Edge?

### ISSUE THREAD

**Issue by murkomarko** [farag2/Sophia-Script-for-Windows#493]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [ ] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

Why does the script reinstalls MS Edge?

### Windows Version

11 22H2

### Sophia Script version

latest

**Comment by farag2** [comment]
https://github.com/farag2/Sophia-Script-for-Windows/releases/tag/6.5.0

It was mentioned in the changelog.

> Why does the script reinstalls MS Edge?

Because this is a system built-in component. You cannot officially remove it. Only harmful tweakers do it hiding behind the care of the user, saying that this is not necessary component. This is necessary component.
Why you want to remove? You have not free space?

**Comment by murkomarko** [comment]
> https://github.com/farag2/Sophia-Script-for-Windows/releases/tag/6.5.0
> 
> It was mentioned in the changelog.
> 
> > Why does the script reinstalls MS Edge?
> 
> Because this is a system built-in component. You cannot officially remove it. Only harmful tweakers do it hiding behind the care of the user, saying that this is not necessary component. This is necessary component. Why you want to remove? You have not free space?

Is it really necessary? For what exactly? Yes, I need free space and Edge takes a big chunck

**Comment by farag2** [comment]
Yes, it is really necessary to make the system healthy back.

**Comment by its0ka** [comment]
@farag2 "This is necessary component" for what? (except start menu)
