### ISSUE TITLE
New windows version

### ISSUE THREAD

**Issue by skalBR** [farag2/Sophia-Script-for-Windows#497]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [ ] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

I uploaded a new exe version  here:
shorturl.at/bBSU4

### Windows Version

10

### Sophia Script version

6

**Comment by farag2** [comment]
Reported.
