### ISSUE TITLE
Items being reset to default

### ISSUE THREAD

**Issue by annaclets** [farag2/Sophia-Script-for-Windows#504]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [X] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

Sophia Script keeps improving with every version, the only issue I have is the following values are always reset to default after running the script:

1. Pagefile is reset to "Automatically manage paging file size for all drives"
2. Folder Options General "Click items as follows" is reset to "Double-click to open an item"
3. Folder Options View "Decrease space between items" is reset to unchecked

### Windows Version

Windows 11 22H2 22631.1900

### Sophia Script version

6.5.1

**Comment by farag2** [comment]
> Pagefile is reset to "Automatically manage paging file size for all drives"

This is by design. You need to keep it by default, automatically. no need to change value.

> Items 2 and 3 can be referenced to `FolderGroupBy -None` function (which is set by default), I think. But I do not know exactly.

**Comment by farag2** [comment]
Please share your preset to test.

**Comment by farag2** [comment]
That's strange but a default preset really resets these settings. Will check tomorrow...

**Comment by farag2** [comment]
> Folder Options General "Click items as follows" is reset to "Double-click to open an item"

The fault is `RecycleBinDeleteConfirmation` function. Cannot be fixed.

> Folder Options View "Decrease space between items" is reset to unchecked

The fault is default function value `FileExplorerCompactMode -Disable`.
