### ISSUE TITLE
The argument types do not match

### ISSUE THREAD

**Issue by amd64fox** [farag2/Sophia-Script-for-Windows#506]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [ ] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

скрипт останавливается с ошибкой
![Аннотация 2023-06-25 185325](https://github.com/farag2/Sophia-Script-for-Windows/assets/62529699/8af91003-84d7-49da-9324-ae35309f58c4)

если отключить вызов функции `AdditionalChecks` в  `Sophia.psm1` то работает нормально

### Windows Version

Windows 10 22H2 19045.3086

### Sophia Script version

5.17.1

**Comment by farag2** [comment]
А зачем ломать скрипт? Эту функцию нельзя выключать.

**Comment by amd64fox** [comment]
Логика моего текста была такая:
- запуск нативного скрипта Sophia - выдает ошибку как на скрине
- запуск с изменением `Sophia.psm1` - не выдает ошибку

**Comment by farag2** [comment]
У меня не выдает. Что я пошло не так?.. Нужен весь архив со скриптом. В Telegram еще написал.

**Comment by farag2** [comment]
That's strange but a default preset really resets these settings. Will check tomorrow...
