### ISSUE TITLE
Script hangs at "would you like to change the location of your folders to the default" Not sure if this is the wrapper @BenchTweakGaming It starts at the Desktop folder and won't go any further

### ISSUE THREAD

**Issue by FredTTya** [farag2/Sophia-Script-for-Windows#518]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [X] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

This won't accept my PS1 file?

### Windows Version

Windows 11 22H2 22621.1992

### Sophia Script version

the latest from 2 hours ago

**Comment by farag2** [comment]
Any screenshot?

**Comment by FredTTya** [comment]
I edited the script to eliminate any. Yes, No questions.  Then it ran fine.
Anytime. It's looking for a Yes No response it fails.  No screenshot.  You
type in a y and it asks you again to type in a y.??

**Comment by farag2** [comment]
Script has no feature yo type y or n. Where did you get it?)

**Comment by farag2** [comment]
> This won't accept my PS1 file?

Upload it please

**Comment by FredTTya** [comment]
I set all folder locations to the default. When I do that, the script asks,
again, if I want to set the folders, one at a time, to the default
location.  That's when it asks me for a yes or no. I've been using the
script for over a year. I always set the folder locations to the default.
In the past it would accept my Y (yes) answer.  It's always worked that way.

**Comment by farag2** [comment]
I cannot figure out what's wrong with your preset without seeing it...  I tested again I had no errors. Probably you're using old preset?

**Comment by FredTTya** [comment]
Thanks for checking.  By altering the script I got the outcome I wanted. 
  Git Hub attachment process didn't allow adding *.PS1 file.  Sorry for 
the trouble.

PS: I'm fairly certain that I wasn't using an old preset.


------ Original Message ------
From "Dmitry Nefedov" ***@***.***>
To "farag2/Sophia-Script-for-Windows" 
***@***.***>
Cc "FredTTya" ***@***.***>; "Author" 
***@***.***>
Date 7/12/2023 10:56:58 AM
Subject Re: [farag2/Sophia-Script-for-Windows] Script hangs at "would 
you like to change the location of your folders to the default" Not sure 
if this is the wrapper @BenchTweakGaming It starts at the Desktop folder 
and won't go any further (Issue #518)

**Comment by farag2** [comment]
> Git Hub attachment process didn't allow adding *.PS1 file

Then just upload it as a raw text 🐱

**Comment by FredTTya** [comment]
I no longer have it... Apologies once more.  On my next build I'll take
some screenshots of the yes/no sequence.  It happens everytime... Strange

**Comment by farag2** [comment]
Np. Bugs reports are welcome!

**Comment by kkoling** [comment]
![script bug](https://github.com/farag2/Sophia-Script-for-Windows/assets/84174066/e63c4597-624c-422e-b07f-aca64dae3c75)

Here is the screenshot of the bug.

**Comment by kkoling** [comment]
mb. It wasn't like this before. i thought the format is broken.

**Comment by farag2** [comment]
😹 

Please read changelog. It contains even video! https://github.com/farag2/Sophia-Script-for-Windows/releases/tag/6.5.3

**Comment by FredTTya** [comment]
That's it!!

**Comment by farag2** [comment]
It used to. :)
