### ISSUE TITLE
Cannot confirm anything on Windows 11

### ISSUE THREAD

**Issue by baliestri** [farag2/Sophia-Script-for-Windows#519]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [X] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

For PowerShell 5 or 7

1. Download the script
2. Customize anything you want
3. Execute the script

PS: I've removed the "warning" from the `InitialActions` comand, but it is still not possible to confirm the following prompts.

### Windows Version

Windows 11 22H2 22621.1992

### Sophia Script version

6.5.3

**Comment by farag2** [comment]
Any screenshot? Any please share your preset.
Did you use arrows on your keyboard?

**Comment by farag2** [comment]
I cannot help without screenshot...

**Comment by baliestri** [comment]
Sorry, I could not answer previously, I tested yesterday again and saw that now works with the arrow keys, but it was still bad, I will not show a screenshot because it was on another computer that is no longer with me and you have already updated the package.
Imagine the following, any key you pressed, he rewrote the question on the screen, then would have the same question several times in the prompt, one below the other, after using the arrow keys the same happened, but he selected something, which exactly was not possible to know.

**Comment by farag2** [comment]
Good to hear. 🐱 Probably, I will add a notification that you need to you arrows))
