### ISSUE TITLE
Unpin all pins for Windows 11 Start Menu not working?

### ISSUE THREAD

**Issue by PeckishAura** [farag2/Sophia-Script-for-Windows#531]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [ ] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

Hello. I've got a new PC with Windows 11 Pro. Ran it through the setup process, installed the latest updates, drivers, powershell version and used the Wrapper to create a preset to speed up customization. 

I ticked the option to unpin all start menu items, but nothing seemed to happen. In fact, pins were added after running the script. The unpin option used to work fine back when the Wrapper was on version 2.6.8. Versions 2.6.9 and the newest 2.6.10 don't seem to affect the start menu pins.

Regrading pins coming back, I even manually unpinned all the items before running the script and suddenly there were new pins in the start menu, as if I had just setup Windows for the first time.

As a side note, I only use the Wrapper as it has the tweaks I use the most and don't need further customization. I have even tested the script on other PCs with freshly installed versions of Windows 11 and have experienced the same result.

### Windows Version

Windows 11 Pro

### Sophia Script version

Windows 11 6.5.5

**Comment by farag2** [comment]
Confirm. Thanks for bugreporting. :cat:

**Comment by farag2** [comment]
Fixed. :)

**Comment by PeckishAura** [comment]
Oh wow that was fast. I'll be sure to check it out with the next update then. Your script has been incredibly useful! Also, based on your documentation, is it possible to separate specific functions out to run them separately? Say, if I wanted to just run the "unpin all apps" function, I could separate that out and use it?

**Comment by farag2** [comment]
Of course! I didn't release a new version yet, so just download an updated file manually.
Just read the instructions on the page: https://github.com/farag2/Sophia-Script-for-Windows#how-to-run-the-specific-functions

Everything is possible))
