### ISSUE TITLE
Sophia.psm1:4945:27: Не удалось найти диск. Диск с именем ""C" не существует

### ISSUE THREAD

**Issue by K0nfy** [farag2/Sophia-Script-for-Windows#532]
### Prerequisites

- [ ] Verify that this is not a Windows issue;
- [ ] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [x] I did not tweak Windows before that could cause system instability;
- [ ] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

## Sophia.ps1
[Sophia.zip](https://github.com/farag2/Sophia-Script-for-Windows/files/12544469/Sophia.zip)

## Скриншот
![gXcN0smdAY](https://github.com/farag2/Sophia-Script-for-Windows/assets/27099419/7134a941-a65e-4c05-8bcf-3ab1d599a86e)

## Описание
Скачал `Sophia.Script.for.Windows.10.v5.17.5.zip` из [release 6.5.5](https://github.com/farag2/Sophia-Script-for-Windows/releases/tag/6.5.5)
Перекомментировал содержимое Sophia.ps1, запустил по инструкции. В процессе вылезла ошибка. Выглядит как опечатка где-то в коде функций. OneDrive вроде удалился, как я и хотел, но какая-то часть функции ведь так и не выполнилась до конца?

### Windows Version

Windows 10 Pro Education 22H2 19045.3393

### Sophia Script version

5.17.5, from [release 6.5.5](https://github.com/farag2/Sophia-Script-for-Windows/releases/tag/6.5.5)

**Comment by farag2** [comment]
Прикольная ошибка у тебя. :) Что-то у тебя сломано, видать. 
Почему кажется опечаткой? Тут так уже не помочь. Удаленку бы, и я гляну хотя бы наметки. А так не понять никогда, что пошло не так.
