### ISSUE TITLE
Disable Automatic sample submission for Microsoft Defender

### ISSUE THREAD

**Issue by Obegg** [farag2/Sophia-Script-for-Windows#537]
I'm not sure why Sophia Script doesn't disable this, I disabled it manually
![image](https://github.com/farag2/Sophia-Script-for-Windows/assets/13978119/65da73c1-25e5-4deb-b4e9-000abf1232df)
Users don't want to send files to Microsoft

```
Microsoft Defender > Virus & threat protection > Manage settings > Automatic sample submission
```

**Comment by farag2** [comment]
This is how to automate this: `Set-MpPreference -SubmitSamplesConsent 2`

I do not consider to add this feature to the script. 

> I'm not sure why Sophia Script doesn't disable this

Because I do not know why we need to add such feature. :)
