### ISSUE TITLE
No internet connection, second time running the script.

### ISSUE THREAD

**Issue by BaselAshraf81** [farag2/Sophia-Script-for-Windows#542]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [x] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

![image](https://github.com/farag2/Sophia-Script-for-Windows/assets/129132034/394aa7b1-e0d3-4568-92af-3068a3d4e5d2)
Second time running the script, now i think most of windows services doesn't connect to internet, maybe thats why powershell can't run the script with internet connection?.

also services like downloading live captions files, doesn't download, maybe that's related.
![image](https://github.com/farag2/Sophia-Script-for-Windows/assets/129132034/a5b2b914-d6ae-4363-911c-226f0dbe755f)

### Windows Version

Windows 11 22H2 22621.2283

### Sophia Script version

6.5.6

**Comment by farag2** [comment]
Hi.
I cannot know whether your PC has an Internet connection, but the code checks the ability to receive bytes from the actual domains. It seems you have no access to GitHub related domains. So, services aren't related with the Internet access at all.

Anyway, regardless you have the access or not, your Windows is broken. The script won't work. This is not an issue. :)

**Comment by BaselAshraf81** [comment]
> Hi. I cannot know whether your PC has an Internet connection, but the code checks the ability to receive bytes from the actual domains. It seems you have no access to GitHub related domains. So, services aren't related with the Internet access at all.
> 
> Anyway, regardless you have the access or not, your Windows is broken. The script won't work. This is not an issue. :)

spassiba for replying, can you provide me with the domains that are being checked by the script? i will try accessing/pinging them.

**Comment by farag2** [comment]
Sorry for the late reply. I was on vacation without a PC. This is very easy!

dns.msftncsi.com, https://raw.githubusercontent.com, https://github.com
