### ISSUE TITLE
[WinAPI.GetStr]::GetString() RuntimeException

### ISSUE THREAD

**Issue by lucasgruembel** [farag2/Sophia-Script-for-Windows#543]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [X] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

Hello,

When executing some Sophia functions, the following error occurs:

```
Der Typ [WinAPI.GetStr] wurde nicht gefunden.
In C:\Users\User\Desktop\microsoft-windows_prepare-fresh-install\windows-11\Module\Sophia.psm1:10927 Zeichen:32
+     $TextBlockSelectAll.Text    = [WinAPI.GetStr]::GetString(31276)
+                                   ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (WinAPI.GetStr:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

Der Typ [WinAPI.GetStr] wurde nicht gefunden.
In C:\Users\User\Desktop\microsoft-windows_prepare-fresh-install\windows-11\Module\Sophia.psm1:10949 Zeichen:27
+         Write-Verbose -Message ([WinAPI.GetStr]::GetString(12612)) -V ...
+                                 ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (WinAPI.GetStr:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

Der Typ [WinAPI.GetStr] wurde nicht gefunden.
In C:\Users\User\Desktop\microsoft-windows_prepare-fresh-install\windows-11\Module\Sophia.psm1:15337 Zeichen:26
+     Write-Verbose -Message ([WinAPI.GetStr]::GetString(12612)) -Verbo ...
+                             ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (WinAPI.GetStr:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
```

The error occurs under Windows 10 Pro 22H2 (Build 19045.3636), Windows 11 Pro 22H2 (Build 22621.2506) and Windows 11 Pro 23H2 (Build 22631.2428) with Powershell 5.
The systems were each freshly installed with the latest German 64-bit ISO from the Microsoft website.

### Windows Version

Windows 11 Pro 23H2 (Build 22631.2428), Windows 11 Pro 22H2 (Build 22621.2506)

### Sophia Script version

6.5.7 Powershell 5

**Comment by farag2** [comment]
You excluded `Checks` function.

**Comment by farag2** [comment]
https://github.com/farag2/Sophia-Script-for-Windows/blob/048c472448610f499f592b5f1d30429685336bba/src/Sophia_Script_for_Windows_11_PowerShell_7/Sophia.ps1#L118

**Comment by lucasgruembel** [comment]
Thanks, sorry, my mistake.
I executed the `InitialActions` in advance under a parent powershell process. I overlooked the corresponding code in `InitialActions`. https://github.com/farag2/Sophia-Script-for-Windows/blob/048c472448610f499f592b5f1d30429685336bba/src/Sophia_Script_for_Windows_11_PowerShell_7/Module/Sophia.psm1#L84

**Comment by farag2** [comment]
Nobody's perfect))
