### ISSUE TITLE
Close taskschd.msc after Function "CleanupTask -Register" or "TempTask -Register"

### ISSUE THREAD

**Issue by lucasgruembel** [farag2/Sophia-Script-for-Windows#544]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [X] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

Hello,
I run the Sophia script via "Start-Process ... -wait" in my own Script. I have the problem that my script does not continue to run after the Sophia script has finished. This is because the "CleanupTask -Register" or "TempTask -Register" functions open the taskschd.msc window, but do not close it. However, "Start-Process ... -wait" waits until the Task Scheduler window is also closed.

![taskschd msc](https://github.com/farag2/Sophia-Script-for-Windows/assets/72384754/7c8af2d1-69dc-4bc3-9e4b-270b9361eabd)

Therefore, my question is whether it is possible to integrate the closing of the task scheduling window at the end of these functions.

### Windows Version

Windows 11 Pro 23H2 (Build 22631.2428)

### Sophia Script version

6.5.7

**Comment by farag2** [comment]
Hi Sorry for the late reply. I was on vacation without my PC.

1) Why do you invoke powershell.exe from powershell.exe????? LOL just call your script with `&`
2) Just edit the code! Remove this if case

https://github.com/farag2/Sophia-Script-for-Windows/blob/048c472448610f499f592b5f1d30429685336bba/src/Sophia_Script_for_Windows_11/Module/Sophia.psm1#L15212

that's all!
