### ISSUE TITLE
windows 11 pro workstation latest update

### ISSUE THREAD

**Issue by realartin** [farag2/Sophia-Script-for-Windows#551]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [X] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

![image](https://github.com/farag2/Sophia-Script-for-Windows/assets/52799129/59679127-6452-4cef-9db2-9688f153fd04)

I use latest update and I'm sure it's the latest but the script won't accept it 

windows 11 pro workstation latest update 22621.3007

### Windows Version

22621.3007

### Sophia Script version

6.5.9

**Comment by farag2** [comment]
You jeed to install the latest Windows build 22631. You have 22621.

**Comment by farag2** [comment]
If you aren't provided the latest KB please install it manually: https://www.deskmodder.de/blog/2023/09/26/kb5027397-funktionsupdate-als-download-fuer-windows-11-23h2-22631-enablement-package/
