### ISSUE TITLE
WARNING: Get-WindowsEdition broken or removed from Windows.

### ISSUE THREAD

**Issue by sgeraldes** [farag2/Sophia-Script-for-Windows#554]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [ ] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

I'm getting "Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force".
Followed the instructions. 
I download the latest copy.
I tried directly clonning github, downloading a release, and within powershell with iwr script.sophia.team -useb | iex

When I run Sophia.ps1 nothing happens for about a minute, then the following error is displayed:

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     6.6.0                 Sophia                              {ActiveHours, AdminApprovalMode, AdvertisingID, A…
WARNING: Get-WindowsEdition broken or removed from Windows.

Nothing else happens.
I tried:
- Updating, several times
- rebooting, several times
- Running the script without a powershell script
- Using Powershell 6
- Using Powershell 7
- Updating Windows Terminal

### Windows Version

Windows 11 Pro 23H2 22631.3155

### Sophia Script version

6.6.0

**Comment by sgeraldes** [comment]
By the way, this is a brand new windows 11 23H2 install, using the Windows USB Download Tool from the official source. Nothing has been customized, nor changed from the default OS install. I have two identical computers that I bought, and both are behaving the same way.

**Comment by farag2** [comment]
Hello. Sorry for the late reply. Well, this is a Windows bug :). Just run ```Get-WindowsEdition -Online``` in PowerShell as admin. If you have an error, that means Windows installation has gone wrong, or soemthing else. Basically there's no such error. So, if you occur with such warning, this is a warning that Windows is ill despite that was a fresh installation. :)

**Comment by sgeraldes** [comment]
I did a brand new Windows 11 install this morning, new download of from Microsoft's website, ISO format this time. Same result. So I did it again using Windows Download Tool on another computer, and prepared an up-to-date windows copy on a thumbdrive with the tool. Third time, same result. 

The command takes about 2 to 5 minutes and returns:

PowerShell 7.4.1
PS C:\Users\SebastianGeraldes> Get-WindowsEdition -Online
Get-WindowsEdition: Class not registered

These are brand-new high-end computers, just bought, working flawlessly, tested all day on every game and app I could find before formatting and reinstalling, and run several stress tests on memory and CPU/GPU without a hitch. 

Brand new windows 11 pro install, nothing else but drivers and latest MS patches. Hardware specs:

MSI Pro X670-P WIFI, updated BIOS to 1/24/2024
AMD Rizen 9 7900X3D
64GB DDR5 6000 CL30
Crucial P700 2TB SSD
NVIDIA RTX 4090

@farag2 any way to disable the check at all? I really would like to get back to the times where this script just runs, without all the checks.

**Comment by farag2** [comment]
Please provide a screenshot.

**Comment by sgeraldes** [comment]
![image](https://github.com/farag2/Sophia-Script-for-Windows/assets/14790771/4d516bac-3787-46d5-9bc1-0c400e2b1167)

**Comment by farag2** [comment]
Hm... Please test in PowerShell 5.1. there's no any advantages in running script in PS 7 unlike 5.1.

**Comment by sgeraldes** [comment]
May be a good idea to mention that in the readme. Looks like Get-WindowsEdition is not working on PS7. 
dism /online /get-currentedition returns the information thou.

![image](https://github.com/farag2/Sophia-Script-for-Windows/assets/14790771/72cfa821-478c-4a14-8148-84a83aa80e8d)

5.1 seems to work:

![image](https://github.com/farag2/Sophia-Script-for-Windows/assets/14790771/1f9cb667-9889-4acb-a48a-09605f06517f)

**Comment by farag2** [comment]
Everyone knows that)) I will add new checks. 6.6.1 is in the work. Will be released tomorrow, I guess. :)

**Comment by sgeraldes** [comment]
Took me two days of troubleshooting and research, and I couldn't find anything on it. Nothing that could point me to Get-WindowsVersion not working... ;)
Still, since there is a Powershell 7 version, a quick note could be usefull. Thanks for the help!
Working ok on 5.1.

**Comment by farag2** [comment]
I've tested on a clean VM and my personal PC: that command works. So something wrong with your OS...
I didn't load 3rd party modules from PowerShell 5.1

![изображение](https://github.com/farag2/Sophia-Script-for-Windows/assets/10544660/2726413d-0a48-43c9-b95c-cccb739ee44e)

**Comment by farag2** [comment]
I'd start with a new clean installation again. Also, if it's necessary, I'd be able to connect remotely to check if this error returns.

**Comment by sgeraldes** [comment]
Thanks Dmitry. I checked twice after this, all failed within PS7. 

New windows installation using a new ThumbDrive with Windows 11 Pro N (just to make sure my previous Windows 11 Pro English US was not broken). But the same result. 

There is not much more loaded into the OS but the minimum drivers and updates required for it to boot and the script not complain about updates. 

What I did:

OS: Windows 11 Pro N (Spanish)
BIOS is updated to the latest version (1/24/2024).
UEFI BIOS, CSM Disabled
All non-essential hardware disconnected.
OS Installation method: 256MB USB 3.1 Thumb drive, built using Windows Download Tool. 
Booted into Thumbdrive with a new drive (only drive connected).
Installed the OS, followed the prompts, used my Microsoft Account (not personal) to log in and complete setup.
No Windows Key provided, it's using the Key installed within the motherboard's UEFI key management and activated successfully.
Updates installed: Three reboots until nothing appeared on the Windows Update, plus all the optional drivers from the advanced section.
Opened Windows Store to update PS5, install PS7, and Windows Terminal. 
Launched Windows Terminal as Administrator and tried on PS7 and PS5.

After this, I got the same result with PS7 and Get-WindowsEdition -online, just hangs for about a minute or more and the fails. 

What I did after: Dism /Online /Get-CurrentEdition on PS7 returns ok (results bellow).

So, I modified the code on Sophia.psm1 module and removed "exit" on line 335. That bypasses the Get-WindowsEdition try to continue. It keeps calling it on the two ocurrances (checks for Core, Enterprise, Education) and takes about 4 or 5 minutes to go through all those checks, but everything else works correctly as expected even if the function returns an error (it defaults to proffesional edition).

By the way, as stated, Get-WindowsEdition runs successfully on PS5, as thus DISM on PS7.

❯ Dism /Online /Get-CurrentEdition

Deployment Image Servicing and Management tool
Version: 10.0.19041.3636

Image Version: 10.0.19045.4046

Current edition is:

Current Edition : ProfessionalN

The operation completed successfully.

----------------------

At this point it is not necessary (for me) to continue further, as PS5 did it for the other computers built, and I won't be using PS7 for the time been for this particular use case. Maybe it is just a bug with PS7 and my specific setup, maybe it is a setting during installation, or just a user error. Thanks for the help and tip pointing to PS5, that did it. In case you want to troubleshoot for your own research, let me know. Happy to help out.

Thanks,

- Seba

**Comment by sgeraldes** [comment]
Thanks Dmitry. I checked twice after this, all failed within PS7.

New windows installation using a new ThumbDrive with Windows 11 Pro N (just
to make sure my previous Windows 11 Pro English US was not broken). But the
same result.

There is not much more loaded into the OS but the minimum drivers and
updates required for it to boot and the script not complain about updates.

What I did:

OS: Windows 11 Pro N (Spanish)
BIOS is updated to the latest version (1/24/2024).
UEFI BIOS, CSM Disabled
All non-essential hardware disconnected.
OS Installation method: 256MB USB 3.1 Thumb drive, built using Windows
Download Tool.
Booted into Thumbdrive with a new drive (only drive connected).
Installed the OS, followed the prompts, used my Microsoft Account (not
personal) to log in and complete setup.
No Windows Key provided, it's using the Key installed within the
motherboard's UEFI key management and activated successfully.
Updates installed: Three reboots until nothing appeared on the Windows
Update, plus all the optional drivers from the advanced section.
Opened Windows Store to update PS5, install PS7, and Windows Terminal.
Launched Windows Terminal as Administrator and tried on PS7 and PS5.

After this, I got the same result with PS7 and Get-WindowsEdition -online,
just hangs for about a minute or more and the fails.

What I did after: Dism /Online /Get-CurrentEdition on PS7 returns ok
(results bellow).

So, I modified the code on Sophia.psm1 module and removed "exit" on line
335. That bypasses the Get-WindowsEdition try to continue. It keeps calling
it on the two ocurrances (checks for Core, Enterprise, Education) and takes
about 4 or 5 minutes to go through all those checks, but everything else
works correctly as expected even if the function returns an error (it
defaults to proffesional edition).

By the way, as stated, Get-WindowsEdition runs successfully on PS5, as thus
DISM on PS7.

❯ Dism /Online /Get-CurrentEdition

Deployment Image Servicing and Management tool
Version: 10.0.19041.3636

Image Version: 10.0.19045.4046

Current edition is:

Current Edition : ProfessionalN

The operation completed successfully.

----------------------

At this point it is not necessary (for me) to continue further, as PS5 did
it for the other computers built, and I won't be using PS7 for the time
been for this particular use case. Maybe it is just a bug with PS7 and my
specific setup, maybe it is a setting during installation, or just a user
error. Thanks for the help and tip pointing to PS5, that did it. In case
you want to troubleshoot for your own research, let me know. Happy to help
out.

Thanks,

- Seba

**Comment by farag2** [comment]
Anyway, I'd like to investigate what's going on))

> Windows Download Tool

Media creation tool? Or a 3rd party site?

> Windows 11 Pro N

From my point of view, there shouldn't be any differences between general 10 and 10 N. Just lack Media Player.

I wanr to install the same Windows version. What to choose and where?

**Comment by sgeraldes** [comment]
Media creation tool: https://www.microsoft.com/software-download/windows11

There should be any differences, but I wanted to make sure to try a different build (hash file to file is identical, but only missing media tools as you pointed out, plus codecs, plus Movies and TV, plus skype... all things I uninstall anyway with Sophia). I just wanted to make sure to download a completely new version instead of re-creating it using anything that might be cached, just to cover all angles. 

My bad! I meant I updated/upgraded to Powershell 7.4.1 from the store (which I normally do with winget or chocolatey, just to make sure winget or choco were not to blame). I also installed Windows Terminal (and Terminal preview) from the store and tried both (not in the latest try, just previously). For PS7, I tried both Powershell and Powershell Preview from the store:
![image](https://github.com/farag2/Sophia-Script-for-Windows/assets/14790771/3bb28a2b-a4a8-49f1-949b-7ad2fa24c417)

**Comment by farag2** [comment]
I recently rested a bit. Could you please remove PS 7 downloaded from Store and install it from GitHub as an .exe?

**Comment by farag2** [comment]
I checked. only downloaded from Store PS 7.4.1 gas this error! 7.5 preview 2 has no such error. So we have isolated the bug!

**Comment by sgeraldes** [comment]
Thanks! Any way I can help? I can confirm the behaviour, but I was having the same issue with both 7.4.1 and 7.5 Preview from the store. That would explain why I was having the issue with Winget before, since it is the same as the store. Maybe 7.5 Preview was updated in store? Bad timing I guess.

**Comment by farag2** [comment]
> Thanks! Any way I can help? I can confirm the behaviour, but I was having the same issue with both 7.4.1 and 7.5 Preview from the store. That would explain why I was having the issue with Winget before, since it is the same as the store. Maybe 7.5 Preview was updated in store? Bad timing I guess.

I'm going to add a try/catch to let a user know that there's a bug in PS 7 from the Store.

**Comment by farag2** [comment]
https://github.com/PowerShell/PowerShell/issues/21295

Fixed in 6.6.1.
