### ISSUE TITLE
VERBOSE: Task Scheduler broken or removed from Windows.

### ISSUE THREAD

**Issue by Obegg** [farag2/Sophia-Script-for-Windows#561]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [ ] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

1. Download Sophia Script:
```
iwr script.sophia.team -useb | iex
```
2. Run Sophia Script.
```
Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
.\Sophia.ps1
```
3. Result:
```

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     5.18.2     Sophia                              {ActiveHours, AdminApprovalMode, AdvertisingID, AeroShakin...

Edition : EnterpriseS

VERBOSE: GET https://raw.githubusercontent.com/farag2/Sophia-Script-for-Windows/master/sophia_script_versions.json with
 0-byte payload
VERBOSE: received 374-byte response of content type text/plain; charset=utf-8
VERBOSE: GET https://raw.githubusercontent.com/farag2/Sophia-Script-for-Windows/master/supported_windows_builds.json
with 0-byte payload
VERBOSE: received 115-byte response of content type text/plain; charset=utf-8

VERBOSE: Please wait...

VERBOSE: GET https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/extra.txt with 0-byte
payload
VERBOSE: received 15517-byte response of content type text/plain; charset=utf-8
VERBOSE: GET https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/extra_v6.txt with 0-byte
payload
VERBOSE: received 13522-byte response of content type text/plain; charset=utf-8
VERBOSE: GET https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt with 0-byte
payload
VERBOSE: received 12383-byte response of content type text/plain; charset=utf-8
VERBOSE: GET https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy_v6.txt with 0-byte
payload
VERBOSE: received 10653-byte response of content type text/plain; charset=utf-8
VERBOSE: GET https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/update.txt with 0-byte
payload
VERBOSE: received 21459-byte response of content type text/plain; charset=utf-8
VERBOSE: GET https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/update_v6.txt with 0-byte
payload
VERBOSE: received 18769-byte response of content type text/plain; charset=utf-8

VERBOSE: Please wait...

VERBOSE: Task Scheduler broken or removed from Windows.
```
This is a fresh install of Windows after installing all updates from windows updates.

Versions 5.18.1 and 5.18.2 are buggy.
I have tried overriding the `Task Scheduler broken` issue by using the following command:
```
(Get-Content Module\Sophia.psm1) -replace 'Register-ScheduledTask @Parameters -Force -ErrorAction Stop', '#'  | Set-Content Module\Sophia.psm1
```
And I couldn't renamed folders on my PC anymore.

Version 5.18.0 is working, but only if I override the version check by using the following command:
```
(Get-Content Module\Sophia.psm1) -replace 'https://raw.githubusercontent.com/farag2/Sophia-Script-for-Windows/master/sophia_script_versions.json', '#' | Set-Content Module\Sophia.psm1
```
Which is another issue by itself - if the newer version is buggy, why can't I use older version?

Took my 2 days to diagnose this issue.

### Windows Version

Windows 10 Iot Enterprise LTSC 2021

### Sophia Script version

5.18.2

**Comment by farag2** [comment]
> I have tried overriding the Task Scheduler broken issue by using the following command:

You mustn't change any code if you do not understand why you encounter with this error.

> And I couldn't renamed folders on my PC anymore.

"Very" informative. No ((

> Which is another issue by itself - if the newer version is buggy, why can't I use older version?

Because, firstly, the new version is not buggy, neither the old one does. Secondly, this is not a script issue, but a Windows one (really)!

Let's check

```powershell
$Action     = New-ScheduledTaskAction -Execute powershell.exe
$Settings   = New-ScheduledTaskSettingsSet -Compatibility Win8 -StartWhenAvailable
$Principal  = New-ScheduledTaskPrincipal -UserId $env:USERNAME -RunLevel Highest
$Parameters = @{
	TaskName    = "SophiaTempScheduledTask"
	Principal   = $Principal
	Action      = $Action
	Settings    = $Settings
}
Register-ScheduledTask @Parameters -Force -ErrorAction Stop
```

Run this code as admin, and let's see whether a temp schedule task will be created. The problem is in Windows username I guess. I encounter 3 time with such issue. No workaround we have found. Just something goes wrong, and Windows is unable to create a simliest task. That's all we know. I mean, try to re-install or something else, but the script won't work for your, that's why I put an exception, and you tried to bypass it for the unknwon reason.

> Took my 2 days to diagnose this issue.

Instead of just asking me by any way...

**Comment by farag2** [comment]
https://github.com/farag2/Sophia-Script-for-Windows/blob/2740d63377eca6fb6ba1474a1f5b2e71461b30ea/src/Sophia_Script_for_Windows_10/Module/Sophia.psm1#L844

**Comment by farag2** [comment]
> After running Sophia Script 5.18.2:

You didn't run it. The script was terminated. Also, there's no such code to break anything, This is not the script fault at all.

**Comment by farag2** [comment]
> GroupId BUILTIN\Administrators -RunLevel Highest.

You mustn't use a built-in group, but $env:USERNAME only. so this is not a workaround unfortunately

> Renaming folders issue:

Will check on Sunday.

**Comment by farag2** [comment]
🤔

**Comment by farag2** [comment]
Thinking out how to fix)

**Comment by farag2** [comment]
1. Yeah, something is wrong in the code.
2. We need to use username only. I gave up isolating the Windows bug. Easier will be just to exit.

**Comment by farag2** [comment]
https://github.com/PowerShell/PowerShell/issues/21377

**Comment by farag2** [comment]
> or make the script check if the PC has been renamed (how?)

Due to many functions uses `Register-ScheduledTask`, I want to leave `exit`.

**Comment by farag2** [comment]
I will test)

**Comment by farag2** [comment]
https://github.com/farag2/Sophia-Script-for-Windows/commit/a18ab5cbae16d768be2765f7d1834323eea6a771
