### ISSUE TITLE
Sophia Script detecting the use of other scripts even after using a restore point.

### ISSUE THREAD

**Issue by yuzamei2854** [farag2/Sophia-Script-for-Windows#562]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [ ] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

After installing Windows 10 LTSC with its updates and some drivers, I created a restore point and decided to install some programs and use another script, after a while I wanted to test Sophia Script to see how it compares, so I decided to open the restore point and go to the point I had created before running anything, but when I tried to run Sophia Script along with Wrapper, it shows me an error that I had already run a script before and that I should reinstall Windows.

I decided to open the Windows configuration and see if the options were set back to default before I ran the other script, and yes, they were set back to default, I have no idea what Sophia Script is complaining about, it would be very annoying for me to have to reinstall Windows over and over again when I could have just loaded the last restore point before running anything.

### Windows Version

Windows 10 21H2 19044.4170 (IoT Enterprise LTSC)

### Sophia Script version

6.6.2 - 06.03.2024

**Comment by farag2** [comment]
Could you upload a screenshot?

**Comment by yuzamei2854** [comment]
> Could you upload a screenshot?

Sure.

![floorp_u0bMqEv8Em](https://github.com/farag2/Sophia-Script-for-Windows/assets/141790911/f4b10059-fa35-4fd4-ad97-255d0422d579)

**Comment by farag2** [comment]
Did you run Winutil script before?

**Comment by yuzamei2854** [comment]
Yes.


Cleaning out the `%TEMP%` folder fixed it, thanks.


It seems that the Windows restore point saves some files, such as the other script's .log, in the `%TEMP%` folder.


So Sophia Script is looking for .log files of other scripts? that should be fine for most cases, but for cases like this where the settings were as default and what triggered it was just a saved .log file, wouldn't it be better to have another way of detecting when a script has actually been executed on the system?

**Comment by farag2** [comment]
You mustn't run any harmful tweakers regardless the method Sophia uses. :)

**Comment by yuzamei2854** [comment]
Yes, I know, that's not what I was talking about, let's say a user ran another script but regretted it, and they had a restore point before they ran that script, and now they've gone back and want to run your script, the problem is that your script would say that the system could be compromised, even if the system had its settings intact by using their last restore point, would it be right for them to reinstall Windows again?
