### ISSUE TITLE
После удаления лишнего в Localizations запуск SophiaScriptWrapper.exe невозможен

### ISSUE THREAD

**Issue by de-served** [farag2/Sophia-Script-for-Windows#576]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [X] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

@BenchTweakGaming
После удаления в Localizations всего, кроме ru-RU и en-US, Script Wrapper не запускается.
Всплывает окно с ошибкой на русском языке об отсутствии... локализации de-DE (?).

### Windows Version

*

### Sophia Script version

Latest

**Comment by farag2** [comment]
Ну а зачем удалять?) я напишу Дэвиду в телегу.

**Comment by BenchTweakGaming** [comment]
Hello de-served.

Sorry about this issue. The EXE checks if all the files are present before continuing.
I can remove this check in next version.

Dave

**Comment by de-served** [comment]
> Ну а зачем удалять?)

Ну как зачем? А зачем лишний мусор? Ведь фактически это однозначно мусор, потому что никогда и ни при каких обстоятельствах не будет использоваться. Занимает место + лишние записи в MFT. Чем чище, тем лучше. Иначе смысл в принципе всего "тюнинга"? ;)

**Comment by farag2** [comment]
Пару килобайт. :) Дэвид исправил в 2.7.1

**Comment by farag2** [comment]
[SSW June 13 2024.zip](https://github.com/user-attachments/files/15826132/SSW.June.13.2024.zip)
