### ISSUE TITLE
Can't import custom script to wrapper

### ISSUE THREAD

**Issue by TristisOris** [farag2/Sophia-Script-for-Windows#580]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [ ] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

import original script, export, import again.
![image](https://github.com/farag2/Sophia-Script-for-Windows/assets/1270117/90427778-2a1f-4b73-b2aa-f89e369418cc)

no matter what chosen, nothing happens, all fields is empty. Still can import original script again.
wrapper 2.7.0 & 2.7.1

### Windows Version

win11 22h2

### Sophia Script version

Windows_11_PowerShell_7_v6.6.7

**Comment by TristisOris** [comment]
fixed. was something weird with script related path(

**Comment by farag2** [comment]
Weird path happens)

**Comment by farag2** [comment]
I've fixed some things in the last commit.
Please use the latest code, by downloading it manually:
https://github.com/farag2/Sophia-Script-for-Windows/blob/master/src/Sophia_Script_for_Windows_11/Sophia.ps1
https://github.com/farag2/Sophia-Script-for-Windows/blob/master/src/Sophia_Script_for_Windows_11/Module/Sophia.psm1
