### ISSUE TITLE
Add option to disable the Undo/Redo Feature

### ISSUE THREAD

**Issue by rafalkk** [farag2/Sophia-Script-for-Windows#584]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [x] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

Hi! Could you add option to disable this very annoying feature in script. Its need to add a value in registry.
This article covers it all: https://www.winhelponline.com/blog/disable-undo-redo-feature-in-windows/

### Windows Version

Windows 10 22H2

### Sophia Script version

10.v5.18.8

**Comment by farag2** [comment]
I don't think it's annoying. Do not consider adding this.

**Comment by rafalkk** [comment]
_"The Undo and Redo feature, however convenient it may be, can also be a big obstacle for many users. Sometimes, users tend to inadvertently click on the Undo or Redo option via the context menu, which results in an undesirable event. The worst thing is that the last file operation may have happened hours back, and you don’t even know what exactly the accidental undo/redo command performed. It happens silently, and the user is not informed about the details of the undo/redo operation. The user might not even notice that it happened."_

Not even consider adding this as an option? Could be skipped by default.
