### ISSUE TITLE
Can't import custom script to wrapper: a new version sophia script found

### ISSUE THREAD

**Issue by Refold3547** [farag2/Sophia-Script-for-Windows#587]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [X] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

In importing the Sophia.PS1 file nothing happens and the script is not activated.
![Sophia Script Wrapper](https://github.com/user-attachments/assets/90a21fc7-e059-4d00-8521-a6df9c3ee5ba)

@BenchTweakGaming

### Windows Version

Windows 11 Pro 24H2 26100.1742

### Sophia Script version

6.6.9

**Comment by farag2** [comment]
U will check this evening

**Comment by farag2** [comment]
What's the script version? Please share the screenshot with sophia.psd1 in Maniferst folder opened.
I do not encounter with such error. it seems you script is outdated. Did you download it from the release page?

**Comment by farag2** [comment]
Installed that Insider build on a VM. Everything works as a charn. This proves that somehow you downloaded an old script. Please download the latest one from https://github.com/farag2/Sophia-Script-for-Windows/releases/latest
