### ISSUE TITLE
Incorrect WARNING: Script supports OS Version, on newest 5.19.0

### ISSUE THREAD

**Issue by akzkak** [farag2/Sophia-Script-for-Windows#591]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
- [X] Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [ ] If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

<img width="623" alt="Capture2" src="https://github.com/user-attachments/assets/df9425af-cdfb-4270-a402-b4984efdc114">

Used same iso on a dozen of older version of Sophia Scripts, and not had this issue before.

### Windows Version

Windows 10 IoT LTSC 21H2 19044.5011

### Sophia Script version

5.19.0

**Comment by Tanzmarie** [comment]
I have the exact same problem with Windows 11 IoT Enterprise LTSC 2024:

![Capture](https://github.com/user-attachments/assets/7eb98253-3b18-4ecb-8b9f-c589933d717e)

**Comment by farag2** [comment]
Hello. `Windows IoT Enterprise LTSC` ≠ `Windows Enterprise LTSC`. IoT edition was made for... IoT. eh?)) So it's by designed. I've never tested Windows on fridge or Raspberry Pi, so I do not understand why you installed such Windows. Anyway, you may edit one string to proceed the script: find 

```powershell
if ((Get-WindowsEdition -Online).Edition -ne "EnterpriseS")
```

in .psm1 file and comment `exit`. Will add formal support with a new commit. lol :)

**Comment by akzkak** [comment]
All the smart people on the internet says there are no difference between LTSC and IoT LTSC (dont sue me) other than end of life Jan 12, 2027 vs Jan 13, 2032
